rule MALPEDIA_Win_Dripion_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "89e91029-adf0-5373-91d6-441ac823d2ed"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dripion"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.dripion_auto.yar#L1-L108"
		license_url = "N/A"
		logic_hash = "6b099e3758909dfda12afb8709370979b2c037becc9af1305c25dce794b98386"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ffd6 8bf8 ffd6 0faff8 ffd6 }
		$sequence_1 = { 03f8 7402 ffd6 ffd6 }
		$sequence_2 = { ffd6 8bf8 ffd6 0faff8 8d3c7f }
		$sequence_3 = { 03f8 ffd6 8bd8 ffd6 0fafd8 ffd6 }
		$sequence_4 = { ffd6 03f8 8d3c7f ffd6 }
		$sequence_5 = { 7513 6a64 ff15???????? 68???????? }
		$sequence_6 = { 8bf8 ffd6 0faff8 8d3c7f }
		$sequence_7 = { ffd6 03f8 ffd6 8bd8 }
		$sequence_8 = { 7402 ffd6 ffd6 ffd6 }
		$sequence_9 = { ffd6 03f8 7402 ffd6 }

	condition:
		7 of them and filesize <90112
}