rule MALPEDIA_Win_Fuwuqidrama_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "2e69e70e-5601-5931-bcd7-e645b5b9c52f"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.fuwuqidrama"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.fuwuqidrama_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "8de556fe8f63afd7a879ecce2fdbb1a150474ddb330c86740527423f92305d9c"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b44241c 8db08c000000 8b8314140000 83f802 764a 8d6b1a 85ed }
		$sequence_1 = { 8b842490020000 52 50 8d4c2444 68???????? 51 }
		$sequence_2 = { 8917 8b542414 894704 b801000000 894f08 89570c 5f }
		$sequence_3 = { 57 33ff 8bd9 57 57 8d4c2430 }
		$sequence_4 = { 8bdf 036908 c1c305 036c2424 c1c61e 89742418 8b712c }
		$sequence_5 = { 83c508 55 ffd7 8a542412 899ec8030000 8896c4030000 899ecc030000 }
		$sequence_6 = { 8bdf 036918 c1c305 036c2410 c1c61e 89742428 8d9c2bd6c162ca }
		$sequence_7 = { ff5220 8d460c 50 ff15???????? 8b4624 }
		$sequence_8 = { 50 ffd6 8d4c242c 6a02 8d542418 51 52 }
		$sequence_9 = { 3d10270000 0f87e7020000 8b5708 8b4704 52 50 8bcf }

	condition:
		7 of them and filesize <245760
}