
rule MALPEDIA_Win_Rhysida_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "64a6dc82-3050-56af-987a-eca5c9c0ccdc"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rhysida"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rhysida_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "c700e285aaa62eb845c4c4a22ba3b4990a79a21d47e9845ba892bd45fa758d74"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ba28000000 4889c1 e8???????? 8945f8 837df800 7407 b804000000 }
		$sequence_1 = { 4863d0 488b4510 4801d0 0fb600 0fb6c0 8b55f4 c1ea06 }
		$sequence_2 = { f6431920 0f84c7feffff 4983c101 e9???????? 4531c0 4889f2 89e9 }
		$sequence_3 = { 8b45fc 4863c8 4889c8 48c1e002 4801c8 48c1e003 4889c1 }
		$sequence_4 = { baafa96e5e 89c8 f7ea c1fa0b 89c8 c1f81f 29c2 }
		$sequence_5 = { 8b45f8 4863d0 488b4510 4801d0 0fb600 0fb6d0 8b45f8 }
		$sequence_6 = { e8???????? eb01 90 8b45f0 0faf45b8 89c2 488d45a0 }
		$sequence_7 = { 85c0 74da 85db 4889742428 0f848d010000 8d4bff 488d742460 }
		$sequence_8 = { c1e903 f348ab ff15???????? 83f812 7472 488b8b38020000 e8???????? }
		$sequence_9 = { 5f 5d 415c 415d c3 b80d000000 ebd7 }

	condition:
		7 of them and filesize <2369536
}