rule MALPEDIA_Win_Vskimmer_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "fc191c93-ce90-5418-a28d-2b3fa9eb623e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.vskimmer"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.vskimmer_auto.yar#L1-L123"
		license_url = "N/A"
		logic_hash = "81aef2465b53cd0c0e1b48561687f8c8208fd8d87041be709dd2217d8a17703f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 3bc3 7402 8bf0 8bd6 f7da 8a07 }
		$sequence_1 = { 68???????? 50 e8???????? 59 59 85c0 0f8445010000 }
		$sequence_2 = { 33c0 0fbe84c188e54100 6a07 c1f804 59 }
		$sequence_3 = { 75f8 ff36 e8???????? 59 8b4508 }
		$sequence_4 = { 8b4508 8bf1 8b4d0c 8b7e04 }
		$sequence_5 = { 5e 5b c3 8b94c110010000 8bb110020000 8b44c108 2bc6 }
		$sequence_6 = { 3bd7 749c 8b8324020000 2580000000 0f95c0 0fb6c0 50 }
		$sequence_7 = { 7e7b 8b460c ff36 03c7 50 }
		$sequence_8 = { 7413 c685b3fdffff01 3bf3 7408 8b451c 8906 }
		$sequence_9 = { 83e803 0f846a010000 48 7439 48 742d 8b4508 }

	condition:
		7 of them and filesize <376832
}