rule MALPEDIA_Win_Former_First_Rat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "e13a8bc3-e4cb-54c7-a2c1-b71b74a37c2c"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.former_first_rat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.former_first_rat_auto.yar#L1-L167"
		license_url = "N/A"
		logic_hash = "79676675a5e0c5d1eb84217b80928525157e507544e18d7d0452685a540a1268"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 899424ec030000 898c24e8030000 8b4f10 8d9424e8030000 6a00 52 898424f8030000 }
		$sequence_1 = { 894c240c 8bd3 3bc1 7420 8d642400 8bf0 }
		$sequence_2 = { 52 bb1c000000 8d742428 894c245c c744246000000000 }
		$sequence_3 = { e8???????? 8b8d0cffffff 68???????? 51 e8???????? }
		$sequence_4 = { ff15???????? 33c0 66833d????????09 0f94c0 a3???????? 6808020000 }
		$sequence_5 = { c785e8feffff0f000000 899decfeffff 899df0feffff 899d04ffffff 899df4feffff }
		$sequence_6 = { e8???????? 8d8de0feffff 51 bb08000000 e8???????? 8b9df8feffff 57 }
		$sequence_7 = { 8bf2 8bfb 81c208020000 b982000000 81c308020000 f3a5 3bd0 }
		$sequence_8 = { 48897c2428 488d05169b0200 488907 488d4f08 e8???????? }
		$sequence_9 = { 480f42db 4883792010 7206 488b4908 eb04 }
		$sequence_10 = { 48837e2008 7209 488b4e08 e8???????? 488d4608 }
		$sequence_11 = { 48895c2468 0f28442450 660f7f442450 0f284c2460 660f7f4c2460 }
		$sequence_12 = { 48896c2460 40886c2450 488bcb e8???????? }
		$sequence_13 = { 488d4754 48894760 48832100 488b4748 48832000 }
		$sequence_14 = { 90 48017e20 488b7620 4881c670ffffff }
		$sequence_15 = { 488b7968 488d0532800200 8bf2 488bd9 }

	condition:
		7 of them and filesize <626688
}