
rule MALPEDIA_Win_Webc2_Ausov_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "452f6306-c16f-58b7-84a1-ee288d662c0a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.webc2_ausov"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.webc2_ausov_auto.yar#L1-L120"
		license_url = "N/A"
		logic_hash = "e12dc956bf634cd764e774e1669338328ccbb898d34279d3918e11978d93f5a2"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 0f8501000000 f8 8b95f8fbffff 0355fc 8995f8fbffff 0f8407000000 }
		$sequence_1 = { 83bdc4fdffff00 7507 33c0 e9???????? 8d8da8faffff 898d4cfaffff }
		$sequence_2 = { 0f8487000000 8b3d???????? 68???????? 56 }
		$sequence_3 = { 0f8407000000 0f8501000000 f8 68???????? }
		$sequence_4 = { 83c101 894df8 8b55f8 3b55f4 7d31 0f8407000000 }
		$sequence_5 = { f7d1 83c1ff 51 8d95f8feffff 52 }
		$sequence_6 = { 0f8501000000 f8 68???????? 8d8dfcfbffff 51 }
		$sequence_7 = { 6804010000 8d85a8faffff 50 68???????? ff15???????? 8985c4fdffff 83bdc4fdffff00 }
		$sequence_8 = { 81ec10040000 53 56 57 0f8407000000 0f8501000000 }
		$sequence_9 = { e8???????? 83c404 8b4d0c 894104 e9???????? 8dbdfcfbffff 83c9ff }

	condition:
		7 of them and filesize <40960
}