rule MALPEDIA_Win_Cutwail_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "62e269de-1aa8-5a3f-857f-84d4e225d36e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cutwail"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.cutwail_auto.yar#L1-L165"
		license_url = "N/A"
		logic_hash = "c6c78a26e86e94e8584b09088785fb67085bf6ba9ec9ef8f1d52fe4203a44bcb"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8808 ebc1 8b5508 03550c c60200 c745fc01000000 8b45fc }
		$sequence_1 = { 3930 0f8491010000 8b08 8b09 894d40 }
		$sequence_2 = { eb12 8d45f4 50 8b4704 }
		$sequence_3 = { 59 e9???????? 8b7de0 8b45f8 83f808 }
		$sequence_4 = { 8b8568feffff 0560ea0000 39855cfeffff 7633 8b8d5cfeffff 898d68feffff e8???????? }
		$sequence_5 = { 8b400c 894564 8d4568 50 }
		$sequence_6 = { c7410400000000 6830750000 ff15???????? 8b55fc 8b02 50 }
		$sequence_7 = { 837d1000 7d04 32c0 eb7d }
		$sequence_8 = { 84c0 745e 46 8a06 }
		$sequence_9 = { 51 e8???????? 83c40c c785e0fdffff00000000 c785dcfdffff00000000 }
		$sequence_10 = { 3bdf 894510 0f84ecfdffff 53 50 }
		$sequence_11 = { 68a6000000 89450c e8???????? 03c3 50 }
		$sequence_12 = { e8???????? 83c410 8985ecfdffff 83bdecfdffffff 0f84ae000000 8b95e4fdffff }
		$sequence_13 = { 76ce 8b7d6c 83ff1d 740e }
		$sequence_14 = { 7509 c68563feffff01 eb77 83bd6cfeffff05 7d6e ff15???????? 89855cfeffff }
		$sequence_15 = { e8???????? 83c414 8b85dcfdffff 2b85d8fdffff 0345fc }

	condition:
		7 of them and filesize <262144
}