rule MALPEDIA_Win_Hlux_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "0554b2ef-0799-5994-8001-d3a987727985"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hlux"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.hlux_auto.yar#L1-L158"
		license_url = "N/A"
		logic_hash = "53ff7358e541a46f4d140f6dc71959f0fd15f8b04731bebe36051fa435d4979d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 81f949e2a499 750b 83f90e 7406 }
		$sequence_1 = { 0101 c9 c3 6a10 }
		$sequence_2 = { 0009 1b4e01 e405 9d }
		$sequence_3 = { 0088aa4b0023 d18a0688078a 46 018847018a46 }
		$sequence_4 = { 0130 8b13 8b08 85d2 }
		$sequence_5 = { b8e3062de4 09c0 7506 898550ffffff 8b8550ffffff ba205af5bb }
		$sequence_6 = { 7545 8945fc 8b45f0 895de8 81f97a701028 7534 }
		$sequence_7 = { 0104b9 33c9 83c408 85c0 }
		$sequence_8 = { 010f 840f 0000 008365f0fe8b }
		$sequence_9 = { 8b0d???????? 85c9 753f 83f963 753a 8945fc 83f93f }
		$sequence_10 = { 0104bb 8d1447 89542418 e9???????? }
		$sequence_11 = { 895de8 33f6 8955cc 83fe13 7503 8975fc 5e }
		$sequence_12 = { 0000 008365f0fe8b 4d 0883c108e918 }
		$sequence_13 = { 8945e0 83f9f3 7507 09c9 7403 }
		$sequence_14 = { 81fb2e5ca766 7503 895de8 8945d4 }
		$sequence_15 = { 83fbd5 7413 33c0 83f827 7403 }

	condition:
		7 of them and filesize <3147776
}