
rule MALPEDIA_Win_Phandoor_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "1f3ac76b-bd09-5712-8c06-9b7787ce6d6a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.phandoor"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.phandoor_auto.yar#L1-L152"
		license_url = "N/A"
		logic_hash = "bcca1bd5fcc5f942c80e8300ebd91840d93d57fc52bf130291de8a118788c527"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 0f8482000000 833d????????00 7479 833d????????00 7470 833d????????00 }
		$sequence_1 = { 833d????????00 0f8452010000 833d????????00 0f8445010000 833d????????00 }
		$sequence_2 = { 83c40c 83c302 3bbe90010000 72d7 }
		$sequence_3 = { 83c404 8d55fc 8bf0 52 56 }
		$sequence_4 = { 0f84c7010000 833d????????00 0f84ba010000 833d????????00 0f84ad010000 833d????????00 }
		$sequence_5 = { 50 8bf9 c645f400 c745f500000000 e8???????? }
		$sequence_6 = { 32d3 32d0 8b45f4 81e1fe010000 c1e018 0b45f8 }
		$sequence_7 = { a3???????? a3???????? a3???????? a3???????? 898de8feffff }
		$sequence_8 = { 83c404 893e 8b4604 3bc7 740c }
		$sequence_9 = { 6a01 51 52 8b5508 }
		$sequence_10 = { 668901 5e c3 33d2 }
		$sequence_11 = { 33c0 3b35???????? 7327 57 }
		$sequence_12 = { 56 8b35???????? 57 68???????? 50 c705????????03000000 }
		$sequence_13 = { 6a01 53 51 8bc8 }
		$sequence_14 = { 56 8b7308 85f6 7420 }

	condition:
		7 of them and filesize <2124800
}