rule MALPEDIA_Win_Starcruft_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "1dcafb43-c4d2-514a-8438-617d875e41e7"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.starcruft"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.starcruft_auto.yar#L1-L131"
		license_url = "N/A"
		logic_hash = "ba9170fb6918e14feeea6fab09146b237b88c2d2d12a4f68164b770922d2ddd1"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 83bd34fbffff00 7458 0fb64d34 85c9 7419 8b95b4fcffff 899558fbffff }
		$sequence_1 = { ebbd c7852cfeffff01000000 83bd2cfeffff00 7565 8b4508 898524feffff c78520feffff00000000 }
		$sequence_2 = { 884def 8b55f0 83c202 8955f0 8b45f0 8945f8 eb09 }
		$sequence_3 = { 8b55f8 8b85ccfeffff 8b0c90 0fb711 85d2 740b 8b45f8 }
		$sequence_4 = { 55 8bec 81ec20010000 a1???????? 33c5 8945e4 8b4508 }
		$sequence_5 = { c685cafcffff26 c685cbfcffffa1 c685ccfcffff8b c685cdfcffff52 c685cefcffff6c c685cffcffffba c685d0fcffffde }
		$sequence_6 = { 8b4dd4 8908 8b5510 8b02 50 8d4dd8 51 }
		$sequence_7 = { 8b4dcc 51 e8???????? 83c404 8945f0 8955f4 8b55d0 }
		$sequence_8 = { e8???????? 83c404 33c0 e9???????? 8b45fc }
		$sequence_9 = { e8???????? e8???????? c705????????04c02e00 c705????????08c02e00 c705????????0cc12e00 c705????????10c12e00 }

	condition:
		7 of them and filesize <294912
}