rule MALPEDIA_Win_Kronos_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "8d31fd16-d4f2-5a2a-96ec-ac39493ba957"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.kronos"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.kronos_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "9add781f31640b82e44b92fb87f47ac9fbcee8b3e1525e4790235c25c58c2848"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d542450 52 03c6 50 57 ffd3 85c0 }
		$sequence_1 = { 813e50450000 7549 57 56 ff75fc e8???????? 8b450c }
		$sequence_2 = { e8???????? 33db 6a40 8d4628 53 50 }
		$sequence_3 = { e8???????? 85db 0f854fffffff eb1c 8d4dd0 be02000000 e8???????? }
		$sequence_4 = { 897804 8930 ff461c 6a00 }
		$sequence_5 = { 803d????????01 56 750f 33f6 8d4df0 e8???????? 8bc6 }
		$sequence_6 = { eb1d 8b0f e8???????? 8b0f 8b30 6a04 e8???????? }
		$sequence_7 = { 0355dc 8b45e8 2b45ec 03ca 3b450c 7356 29450c }
		$sequence_8 = { c3 55 8bec 83ec5c 56 8d45a4 50 }
		$sequence_9 = { 3b7104 7505 8b06 894104 3b7108 7506 8b5604 }

	condition:
		7 of them and filesize <1302528
}