
rule MALPEDIA_Win_Himera_Loader_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "e46aed8f-6384-5100-b12a-1e2dd8afe756"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.himera_loader"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.himera_loader_auto.yar#L1-L127"
		license_url = "N/A"
		logic_hash = "ec88d24287290abbd140c4f0211e2582e892064d8e933b967abedc9a00192e9f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? 83c408 8b4dfc 6689411e 6a10 }
		$sequence_1 = { 64a300000000 894de0 c745dc0c000000 c645e45e c645e55d }
		$sequence_2 = { 8b4d08 0fb71401 52 e8???????? 83c408 8b4dfc 66894130 }
		$sequence_3 = { 8d85dcfdffff 50 8d8df8feffff 51 8d95f8feffff 52 8d8deffdffff }
		$sequence_4 = { c20400 e8???????? 85c0 0f84c1510000 }
		$sequence_5 = { c645eb1c c645ec2e 64a12c000000 8b08 8b15???????? 3b9104000000 7e4c }
		$sequence_6 = { 50 8d45f4 64a300000000 894de0 c745dc0a000000 c645e440 c645e55a }
		$sequence_7 = { c7459c49000000 c645a463 c645a541 c645a654 c645a747 c645a842 c645a942 }
		$sequence_8 = { c645e801 c645e90e c645ea18 c645eb1a c645ec00 c645ed1e c645ee2e }
		$sequence_9 = { c745fc00000000 eb09 8b45fc 83c001 8945fc 837dfc25 7321 }

	condition:
		7 of them and filesize <385024
}