rule MALPEDIA_Win_Bangat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "a2d4fb7c-d848-52ac-b553-710b64461faf"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bangat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.bangat_auto.yar#L1-L131"
		license_url = "N/A"
		logic_hash = "795b6baa10d3ea1f31877796bf7d8c3236899cd7fc3cddcf5f5e7734a685bf62"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 6a01 6800000040 50 e8???????? 83c43c 8bf0 83feff }
		$sequence_1 = { 13f9 03f0 13fd 8b6c2434 89742418 03de 8b74245c }
		$sequence_2 = { 8b442424 99 f7fe 83c408 85d2 7425 6815050000 }
		$sequence_3 = { ff750c 50 ff15???????? 8bf0 ff15???????? 83f850 }
		$sequence_4 = { 8b4c2474 0bc8 8b442464 0bc2 8b54244c 33f1 33f8 }
		$sequence_5 = { 83cbff eb11 83fb01 750c 8b5004 85d2 7505 }
		$sequence_6 = { 8b5704 8b0e 8b3a 8bc1 2bc7 7511 8b7a08 }
		$sequence_7 = { 8b35???????? 8d45e8 68???????? 50 ffd6 8bf8 59 }
		$sequence_8 = { 8b4b58 898184030000 8b03 3d00030000 0f8ebf000000 8b442418 8b4c2414 }
		$sequence_9 = { 75f3 5f 5e 5d b830000000 }

	condition:
		7 of them and filesize <1228800
}