rule MALPEDIA_Win_Unidentified_082_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "7772581c-e8cf-5615-a758-46ef9c1fc0b0"
		date = "2021-10-07"
		modified = "2021-10-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_082"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.unidentified_082_auto.yar#L1-L124"
		license_url = "N/A"
		logic_hash = "fdfe1ddce9f77ac8b465b0ddebe868c5e77078cf2b2457573a5b3810682f45ee"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20211007"
		malpedia_hash = "e5b790e0f888f252d49063a1251ca60ec2832535"
		malpedia_version = "20211008"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 4c8d0dbc190200 0f1f4000 0f1f840000000000 418d4801 }
		$sequence_1 = { ff5018 4c634510 488d0df40a0200 488bd8 33c0 }
		$sequence_2 = { 4c634510 488d0d93fa0100 488bd8 33c0 488bd3 488905???????? 488905???????? }
		$sequence_3 = { ff15???????? 488b0cdf ff15???????? 48c704dfffffffff }
		$sequence_4 = { 4885c0 0f84ac010000 48833d????????00 0f849e010000 48833d????????00 0f8490010000 48833d????????00 }
		$sequence_5 = { 488b0d???????? 8b5108 488b4910 4533c9 458d4130 4c89742420 }
		$sequence_6 = { 33c0 e9???????? 8a07 4c8b7c2448 4c8d25a64c0100 4b8b0cfc ffc3 }
		$sequence_7 = { 0f1f4000 0f1f840000000000 418d4801 0fb6c2 41ffc0 f7da }
		$sequence_8 = { 488b4f18 4c8d4d10 488b01 488d1587000200 41b810000000 ff5018 4c634510 }
		$sequence_9 = { 48894598 eb03 4533f6 488b05???????? 80782e00 740a 80782000 }

	condition:
		7 of them and filesize <414720
}