
rule MALPEDIA_Win_Protonbot_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "b19d2c4d-3d72-5fe6-aaaa-c0b323237a91"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.protonbot"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.protonbot_auto.yar#L1-L123"
		license_url = "N/A"
		logic_hash = "9f42d2358a0490651f249ec756eecbb8cc6207cec8ace7f179285ca0a209261c"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 0f434550 6a00 6a00 6a00 }
		$sequence_1 = { 8b36 8d442408 50 56 e8???????? 83c408 83f808 }
		$sequence_2 = { e8???????? 8d8dd4feffff e8???????? 83c418 c645fc01 }
		$sequence_3 = { 899df8fffeff e8???????? 83c410 8bf8 }
		$sequence_4 = { 8bf1 6a04 c745fc01000000 e8???????? 83c404 8bf8 }
		$sequence_5 = { 837f1410 7202 8b3f 57 50 e8???????? ffb5d4feffff }
		$sequence_6 = { 7f8d 5e 5f 33c0 5b 8b4dfc }
		$sequence_7 = { 50 8d45f4 64a300000000 8bda 8bf9 8d8dd8feffff }
		$sequence_8 = { 8d85b8fbffff 0f4385b8fbffff 50 8d85d0fbffff 68ff000000 50 e8???????? }
		$sequence_9 = { b901000000 8bc2 c1e81e 33c2 69d06589076c 03d1 89948d54ecffff }

	condition:
		7 of them and filesize <1073152
}