
rule MALPEDIA_Win_Seasalt_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "e41fdf89-eed2-569c-87d1-66ae3f31eb44"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.seasalt"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.seasalt_auto.yar#L1-L117"
		license_url = "N/A"
		logic_hash = "c4e00a9b356da4bb38f74ae93a3974f0cb2a6403defdfa59feac8c8b4bbe886d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 888800d90010 eb1f 83f861 7213 }
		$sequence_1 = { a3???????? 3bc6 7513 68e0930400 ff15???????? 8975fc }
		$sequence_2 = { 83d8ff 3bc3 758c b901040000 33c0 }
		$sequence_3 = { f2ae a1???????? 68???????? f7d1 }
		$sequence_4 = { 8b8c2454010000 6a00 8d442428 6800010000 50 }
		$sequence_5 = { 6aff 50 ff15???????? 85c0 6a00 }
		$sequence_6 = { 8bf7 c1e902 8bfa 8d942488010000 f3a5 }
		$sequence_7 = { 7ced 55 8bac2418020000 6a00 8d442414 6804020000 50 }
		$sequence_8 = { 8dbc2419020000 c684241802000000 f3ab 66ab 6a00 }
		$sequence_9 = { c1e902 83e203 83f908 7229 f3a5 ff2495c8350010 8bc7 }

	condition:
		7 of them and filesize <139264
}