rule MALPEDIA_Win_Graphite_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "22d6771d-6e02-5bad-92aa-7abf2f0540bc"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.graphite"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.graphite_auto.yar#L1-L109"
		license_url = "N/A"
		logic_hash = "fac8314c02add0a1a3fcfc7bc6cd359f12eb58a8246911250bf475b51a803e3f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 7513 33d2 e8???????? 84c0 }
		$sequence_1 = { 33d2 e8???????? 84c0 74e4 }
		$sequence_2 = { 81e2ff030000 81e1bf030000 83c940 c1e10a }
		$sequence_3 = { 7513 33d2 e8???????? 84c0 74e4 }
		$sequence_4 = { 81e1bf030000 83c940 c1e10a 0bca }
		$sequence_5 = { ff15???????? 33c0 eb05 b801010000 }
		$sequence_6 = { 85db 7513 33d2 e8???????? 84c0 74e4 }
		$sequence_7 = { 85db 7513 33d2 e8???????? 84c0 }
		$sequence_8 = { 85db 7513 33d2 e8???????? }
		$sequence_9 = { 81e2ff030000 81e1bf030000 83c940 c1e10a 0bca }

	condition:
		7 of them and filesize <98304
}