
rule MALPEDIA_Win_Virdetdoor_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "888dbb4a-ac95-59fd-b6c6-805a13eab949"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.virdetdoor"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.virdetdoor_auto.yar#L1-L123"
		license_url = "N/A"
		logic_hash = "f95b30ef178ddd53d43c681785d15b079df5f7a769adfe7338b74de03b97c177"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b93b0020000 2bc2 50 8b83ac020000 03c2 50 }
		$sequence_1 = { 83ee01 753e 85ff 7524 390b 7720 3903 }
		$sequence_2 = { 8d4dc0 e8???????? 85c0 0f84c8000000 }
		$sequence_3 = { 83fe08 0f43c8 83c602 0fb7444dc0 0bd0 0fb7449dd2 0bd0 }
		$sequence_4 = { 59 8d44240c 8bce 50 ff7314 57 e8???????? }
		$sequence_5 = { 0fbfd0 8d8df8fdffff ff7508 50 }
		$sequence_6 = { 55 8bec 51 51 53 8bc1 33db }
		$sequence_7 = { ff75f0 8d8b50020000 e8???????? 834dfcff }
		$sequence_8 = { 3c2e 7404 3c3a 750e 8a0437 88441dc0 43 }
		$sequence_9 = { 8945f8 8b4508 8bf0 8975f0 8d5808 895df4 }

	condition:
		7 of them and filesize <106496
}