
rule MALPEDIA_Win_Nimbo_C2_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "89998246-cbee-55ef-81ba-46cc3fd70d1a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nimbo_c2"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.nimbo_c2_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "8c39050d61f289d245bf6365ffd110e7ad73787b347fdf5526ee916f50a01d10"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 741a 488b4960 ba22000000 e8???????? 488d4b60 4889c2 e8???????? }
		$sequence_1 = { 7434 498b07 b902000000 4899 48f7f9 498b17 31c9 }
		$sequence_2 = { e8???????? 4883c470 5b 5e 5f 415c 415d }
		$sequence_3 = { 488b4c2428 84c0 740f 4883c430 415c 415d 415e }
		$sequence_4 = { 4889f1 4889442420 e8???????? 48ff4608 4883c440 5b 5e }
		$sequence_5 = { 7d45 eb49 488b4a10 488b5218 48894810 4889d9 48895018 }
		$sequence_6 = { 4d8b2c24 31ff 4c39ef 7de9 498b54fc10 4889f1 48ffc7 }
		$sequence_7 = { e8???????? 31d2 4c89e1 498907 e8???????? 4c89e9 488906 }
		$sequence_8 = { c1fa0c 83e23f 83ca80 885012 89da 83e33f c1fa06 }
		$sequence_9 = { 807c33102d 0f94c0 48ffc6 ebd4 4c89e0 4883c428 5b }

	condition:
		7 of them and filesize <1141760
}