
rule MALPEDIA_Win_Remy_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "7ce97943-cfc3-5429-92c7-f07c9ff48391"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.remy"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.remy_auto.yar#L1-L129"
		license_url = "N/A"
		logic_hash = "8cc4f887faa36fa3ebf369fe88c2b140d588410f99b73c322f37daf8b5d5619a"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 83c404 3bc3 7420 50 8bc6 8d7c241c }
		$sequence_1 = { 56 81c30f010000 53 e8???????? 8d46f0 }
		$sequence_2 = { 3dc8000000 0f85c50b0000 6a28 8d742424 895c2424 895c2428 895c242c }
		$sequence_3 = { 5d c3 8b7dfc 8d4fff 81f9ffff0000 7728 }
		$sequence_4 = { 7451 8d4634 898638100000 8d8634100000 c70000100000 895d0c 895d08 }
		$sequence_5 = { 51 8d570c 52 e8???????? 83c40c 8b4508 83c010 }
		$sequence_6 = { 8b5604 2bc8 2bd0 c1f902 c1fa02 3bd1 }
		$sequence_7 = { 8d8748100000 57 8908 8d4da4 51 8d55a0 52 }
		$sequence_8 = { 8d4d90 e8???????? 83c41c c645fc02 895e40 8bff 8b4d94 }
		$sequence_9 = { 50 ff15???????? 8b95b4feffff 52 ff15???????? 8b4df4 64890d00000000 }

	condition:
		7 of them and filesize <507904
}