rule MALPEDIA_Win_Spectre_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "af0ed3ea-7150-5006-a1e4-f1f71a7eae7a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.spectre"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.spectre_auto.yar#L1-L132"
		license_url = "N/A"
		logic_hash = "168b0e3a3116ff3325056de927c137c412a6159d98ef56a6628c736a2a7417ad"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ebe3 83c8ff 5d 5b 59 59 c3 }
		$sequence_1 = { 68???????? ff5604 e9???????? 807c242000 0f8414010000 6a02 }
		$sequence_2 = { 51 e8???????? 59 59 8b8424ec000000 895c2470 896c2474 }
		$sequence_3 = { 50 e8???????? 83c40c 50 8d8424a0000000 50 e8???????? }
		$sequence_4 = { 83e801 7440 83e801 742c 83e801 7418 }
		$sequence_5 = { 894554 53 8d4dc3 e8???????? 8bc8 e8???????? 50 }
		$sequence_6 = { 83f81b 0f8ee3020000 83f81f 0f8eb3020000 83f821 0f8e06020000 83f822 }
		$sequence_7 = { 8b4704 8bcd c6400c01 8b4704 8b4004 c6400c00 8b4704 }
		$sequence_8 = { 51 8d8c2440010000 e8???????? 8d8c24d8000000 e8???????? 8d4c2448 e8???????? }
		$sequence_9 = { c68424c400000000 ff15???????? 59 59 85c0 743d 6a01 }

	condition:
		7 of them and filesize <990208
}