
rule MALPEDIA_Win_Zedhou_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "2aa4d978-6d48-5f72-a16b-4b6ea617b5b6"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zedhou"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.zedhou_auto.yar#L1-L129"
		license_url = "N/A"
		logic_hash = "b60fc9437fc4bcd4e7a504c33358b6d6c8b7b5e0237aab2ee62dd854e5c508d6"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b4dac 894dd8 8d55d0 52 8d45d4 50 }
		$sequence_1 = { ff5030 5f 5e 5b c9 c22400 }
		$sequence_2 = { 57 ff7508 56 ff15???????? ff7508 ff15???????? 8bc6 }
		$sequence_3 = { 8d4da4 51 8b5508 8b02 8b4d08 51 ff9008070000 }
		$sequence_4 = { ff15???????? 8d4dc0 ff15???????? 0fbf4598 85c0 742a c745fc06000000 }
		$sequence_5 = { 68???????? 8b85acfeffff 50 8b8da8feffff 51 ff15???????? 8985c4fdffff }
		$sequence_6 = { 33c0 f3a6 0f85653a0000 85d2 }
		$sequence_7 = { ff15???????? 83c41c c745fc04000000 8b5508 8b02 8b4d08 51 }
		$sequence_8 = { ff15???????? c745fc7f000000 8b5508 8b4238 50 68???????? ff15???????? }
		$sequence_9 = { e8???????? 894604 8b430c 59 8b04c5fc201822 59 6a01 }

	condition:
		7 of them and filesize <499712
}