
rule MALPEDIA_Win_Sakula_Rat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "877a5bc8-1502-5d2d-ac89-d1f9991b4673"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sakula_rat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.sakula_rat_auto.yar#L1-L234"
		license_url = "N/A"
		logic_hash = "5566117feff4531b6238852b1dd267d13dd172e7c51c8c4e9976cadb5e493558"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 6a00 6800010000 6a00 6a00 68???????? }
		$sequence_1 = { 8bf0 56 6a01 57 53 }
		$sequence_2 = { 57 56 e8???????? 8d7e10 8ad8 57 8bc7 }
		$sequence_3 = { 33c9 85f6 7e15 8a0411 84c0 7409 }
		$sequence_4 = { 53 e8???????? 83c40c 6a00 6a00 57 53 }
		$sequence_5 = { 8bc7 e8???????? 83c408 833e01 }
		$sequence_6 = { 50 e8???????? 83c404 32c0 5d }
		$sequence_7 = { 53 e8???????? 56 e8???????? 83c41c 5f 5b }
		$sequence_8 = { 66895db0 48895c2450 4889442458 4889442460 }
		$sequence_9 = { ff15???????? 33d2 488bcb ff15???????? e8???????? 33c9 ff15???????? }
		$sequence_10 = { 8b45d8 8b5de0 01d8 8945e0 6a01 e8???????? }
		$sequence_11 = { 4c8bc6 33d2 33c9 448bc8 897c2428 48895c2420 ff15???????? }
		$sequence_12 = { 0f8516010000 488d15e61c0000 41b804010000 48890d???????? ff15???????? ff15???????? 83f801 }
		$sequence_13 = { 7459 68???????? 68???????? e8???????? 83f800 }
		$sequence_14 = { 8945e4 83f800 0f843c010000 6a00 6a00 ff75ec }
		$sequence_15 = { e8???????? 50 ff75f4 e8???????? 58 eb02 31c0 }
		$sequence_16 = { 8a03 3c00 7414 b21a }
		$sequence_17 = { ff15???????? 33d2 488d4deb 448d426c }
		$sequence_18 = { ff15???????? 488bce 488bd8 ff15???????? 488364243800 488364243000 }
		$sequence_19 = { e9???????? 31c0 7402 31c0 50 ff75fc e8???????? }
		$sequence_20 = { ff9080000000 3bc6 741b 488b4dc7 488b01 }
		$sequence_21 = { 6804010000 ff75fc 6a00 e8???????? ff75fc }
		$sequence_22 = { 33d2 ff15???????? 3bc6 745f 4c8d4dcf }

	condition:
		7 of them and filesize <229376
}