rule MALPEDIA_Win_Batel_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "5c784793-7499-59d2-9d6e-e8d3b0a588c6"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.batel"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.batel_auto.yar#L1-L228"
		license_url = "N/A"
		logic_hash = "54d1d1c2accc87182d1d618459ab2c69708bc7f726841a04281db6bdb06903a0"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 33c0 5b c21000 3b0d???????? 7502 f3c3 }
		$sequence_1 = { 56 b858212300 be58212300 57 8bf8 3bc6 }
		$sequence_2 = { 7429 68f4202300 56 ff15???????? }
		$sequence_3 = { 7cec 56 57 6a40 6800100000 }
		$sequence_4 = { 7ccd 5f 5e 5d 33c0 5b c21000 }
		$sequence_5 = { c745fc00000000 6800002300 e8???????? 83c404 }
		$sequence_6 = { 689d020000 8d8561fdffff 6a00 50 c68560fdffff00 }
		$sequence_7 = { 8b1d???????? bf01000000 8d642400 68???????? ff15???????? }
		$sequence_8 = { b8???????? 8a10 88940d60fdffff 83c003 }
		$sequence_9 = { a1???????? 85c0 752c 8935???????? 68d0202300 }
		$sequence_10 = { 40 c20c00 55 8bec 81eca0020000 68ee020000 ff15???????? }
		$sequence_11 = { b90b010000 66398818002300 75dd 83b8740023000e 76d4 }
		$sequence_12 = { ffd3 68005c2605 ffd5 47 83ff5a 7ccd 5f }
		$sequence_13 = { 55 8b2d???????? 56 57 68a00f0000 ffd5 }
		$sequence_14 = { 85c0 7412 ffd0 56 }
		$sequence_15 = { 59 6a00 ff15???????? 68d8202300 ff15???????? 833d????????00 }
		$sequence_16 = { 68a00f0000 ffd5 8b1d???????? bf01000000 }
		$sequence_17 = { 50 c68560fdffff00 e8???????? 83c40c 33c9 }
		$sequence_18 = { 85f6 7422 68???????? 56 ff15???????? 85c0 7412 }
		$sequence_19 = { 6a00 ff15???????? 8bf8 b9a7000000 8db560fdffff f3a5 66a5 }
		$sequence_20 = { 6a40 6800100000 689e020000 6a00 ff15???????? }
		$sequence_21 = { 83b8740023000e 76d4 33c9 3988e8002300 0f95c1 8bc1 6a02 }
		$sequence_22 = { 66a5 ffd0 5f 5e }

	condition:
		7 of them and filesize <49152
}