
rule MALPEDIA_Win_Luca_Stealer_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "8a0c166d-37f3-5a13-bfc2-83fc09a4679d"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.luca_stealer"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.luca_stealer_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "f2eabac635b7bb4e193cfff7279ec9fd429ac964f492c856eb49bfd67aa7534f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? 488bf8 81e7ffffff3f 498b4e60 488b5910 4885db 7452 }
		$sequence_1 = { f645ef02 741d 807df101 7417 b201 488d4de7 e8???????? }
		$sequence_2 = { eb06 4531c0 4889d0 48c7837802000002000000 44888380020000 c6838102000000 48898388020000 }
		$sequence_3 = { e8???????? 498b0f 498b4708 4983670800 4885c0 740f 4883c420 }
		$sequence_4 = { ff15???????? 894530 85c0 0f842b520000 488dbd501f0000 8b0f e8???????? }
		$sequence_5 = { e8???????? 85c0 0f85be000000 488bcb e8???????? 488b8798090000 498bce }
		$sequence_6 = { e8???????? 85c0 740c 488b0b 8a0439 2c3a 3c01 }
		$sequence_7 = { e9???????? 488d3515b8d8ff eb03 4d03fd 410fb607 4484ac30009e4100 75ef }
		$sequence_8 = { e9???????? b009 eb4f 488b842490000000 66c7000109 e9???????? 488db424e0000000 }
		$sequence_9 = { eb86 e8???????? 0f0b 4157 4156 4155 4154 }

	condition:
		7 of them and filesize <9285632
}