rule MALPEDIA_Win_Cerbu_Miner_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "77652d6a-745f-5552-8901-83bf555706f4"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cerbu_miner"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.cerbu_miner_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "e4927a587588bc11053fcbade5bb9500364c9a656d383eb318cc8486464f3cce"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 88b42480000000 eb3f 83e902 7433 83e904 7413 83e909 }
		$sequence_1 = { 7412 48 8d0d0b360500 48 83c428 48 ff25???????? }
		$sequence_2 = { 8d4601 c643012e 48 63c8 41 8d4602 48 }
		$sequence_3 = { 85d2 7427 85c9 b800040000 41 b800080000 44 }
		$sequence_4 = { f6473801 7402 eb18 48 8bcf ff15???????? f6473801 }
		$sequence_5 = { e9???????? 45 8bfd 44 89ad50010000 e9???????? 44 }
		$sequence_6 = { 48 89442420 e8???????? 48 8bd7 48 8bcb }
		$sequence_7 = { 89b42418010000 8b74242c 83feff 7515 837f0c00 7c0f 48 }
		$sequence_8 = { 8d057b52f9ff 48 894518 c745b0e6070000 48 c745c000000200 48 }
		$sequence_9 = { 44 2bc0 44 8903 33c0 48 8b5c2438 }

	condition:
		7 of them and filesize <1040384
}