
rule MALPEDIA_Win_Bluenoroff_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "c5a8ede1-c77a-5a4b-899a-3e41c1e4e510"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bluenoroff"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.bluenoroff_auto.yar#L1-L113"
		license_url = "N/A"
		logic_hash = "65b6fe6298815292c6af264e82e027897f56c9c87e000fed42924fa12c98e75b"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 83f802 750e 8d95fcfffeff 52 68???????? }
		$sequence_1 = { 8d8df8feffff 51 ff15???????? 0fbe95f8feffff 68???????? }
		$sequence_2 = { 85f6 743a 8d85fcfffeff 50 }
		$sequence_3 = { 894e04 e8???????? 83c40c 5f }
		$sequence_4 = { eb10 85c0 7514 8d85fcfffeff 50 68???????? }
		$sequence_5 = { 83feff 7433 8d4e01 51 6a40 }
		$sequence_6 = { 68ffff0000 50 e8???????? 33c0 }
		$sequence_7 = { 56 6a10 68???????? e8???????? 83c410 813ed0c0b0a0 }
		$sequence_8 = { 33ff 53 ff15???????? 8b450c 85c0 7402 }
		$sequence_9 = { 50 0fb785f4fffeff 51 52 }

	condition:
		7 of them and filesize <303104
}