rule MALPEDIA_Win_Newposthings_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "d2908836-d6a9-5323-a30e-68bb82428f91"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.newposthings"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.newposthings_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "aacccdc30f2a004211f7fc15df6e0bf41cf9693ce7a4e367dede73ae07376ff4"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8a4601 3c30 7c04 3c39 7e0a 3c3d 7406 }
		$sequence_1 = { 7423 3d00000400 7550 80c980 884c3704 8b0c9d481d0210 8a443124 }
		$sequence_2 = { 83e61f 8b0485481d0210 c1e606 80643004fd 8b45f8 8b55fc 5f }
		$sequence_3 = { ff7510 ff750c 56 6843120110 e8???????? 83c418 85c0 }
		$sequence_4 = { 83c602 663906 74f8 6a03 56 68548e0110 e8???????? }
		$sequence_5 = { 50 c644245c00 8bce e8???????? 8bf0 eb02 33f6 }
		$sequence_6 = { e8???????? 50 8bcb e8???????? c745fc00000000 c745f001000000 8bc3 }
		$sequence_7 = { 8b049538f34500 47 ff3418 ff15???????? 85c0 750a ff15???????? }
		$sequence_8 = { 83c204 8955e0 eb86 890cb538f34500 }
		$sequence_9 = { e8???????? c745fc00000000 83ec18 8bcc 896588 6aff }

	condition:
		7 of them and filesize <827392
}