
rule MALPEDIA_Win_9002_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "49e80af5-ef9d-5bf8-b3b9-b7af1f356471"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.9002"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.9002_auto.yar#L1-L290"
		license_url = "N/A"
		logic_hash = "9d293b5dc33eac56c2e3f0cda3054624c24835d742e33a63df2c2aa725e52d40"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 7514 8b4714 8b08 51 e8???????? 8b5714 }
		$sequence_1 = { 51 8944241c c744241801000000 ff15???????? 3d02010000 }
		$sequence_2 = { 7504 33ed eb04 2bc8 }
		$sequence_3 = { 8bd1 2bd0 3bda 7223 }
		$sequence_4 = { 6a02 ff15???????? 68???????? ff15???????? 6a00 }
		$sequence_5 = { 8b5c2408 6bdb08 03c3 8b00 }
		$sequence_6 = { 33c9 3bc8 1bd2 f7da 8915???????? }
		$sequence_7 = { 03c3 8b00 5b ffd0 8945fc }
		$sequence_8 = { 51 e8???????? 6a06 6a01 6a02 e8???????? }
		$sequence_9 = { 8be9 53 50 e8???????? }
		$sequence_10 = { 7504 33d2 eb05 8b5608 2bd0 3bfa }
		$sequence_11 = { 682c010000 50 ffd3 3d02010000 7508 }
		$sequence_12 = { 6a00 6a02 6a03 6a00 e8???????? }
		$sequence_13 = { 75f6 eb2f 8b542430 8b7c2414 8b6c2430 }
		$sequence_14 = { 668b3c59 730d 33c9 8a0a }
		$sequence_15 = { 59 8b0485e0d50010 8d0cf6 8064880400 85ff }
		$sequence_16 = { 0311 8955fc 837df800 0f86e3000000 8b4508 03450c 2b45f8 }
		$sequence_17 = { 68???????? 8d4610 50 8d4c2418 51 ff15???????? }
		$sequence_18 = { 896f2c 8b4748 3bc5 740c 50 }
		$sequence_19 = { 8d4c240c c644243002 ff15???????? 8bc6 }
		$sequence_20 = { 6a00 8bd8 51 57 53 }
		$sequence_21 = { 8b4c242c 5f 89411c 8b442410 895118 8b542434 894124 }
		$sequence_22 = { 33c4 50 8d442428 64a300000000 8bf1 89742408 68???????? }
		$sequence_23 = { 8939 89742410 e9???????? 33f6 83ff14 }
		$sequence_24 = { 0fb74e08 0fafcf 5f 03c1 5e }
		$sequence_25 = { 031481 52 8b450c 50 }
		$sequence_26 = { 5d 83c410 c3 8b4508 85c0 7499 }
		$sequence_27 = { 2bc5 c1ef05 2bcf 2bf5 66898c5a98010000 33c9 }
		$sequence_28 = { 64a300000000 8b7c2444 8bf1 33db 57 8d4e10 89742414 }
		$sequence_29 = { 8b742408 57 85f6 742e 0fb74602 8b7c2410 3bf8 }
		$sequence_30 = { 8b5c2424 3bcb 0f83f6040000 33db }

	condition:
		7 of them and filesize <204800
}