rule MALPEDIA_Win_Mechanical_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "2ebc8e2c-9656-5fd5-9240-713f089f8d21"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mechanical"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.mechanical_auto.yar#L1-L158"
		license_url = "N/A"
		logic_hash = "0d673fb1f58f38008ae08ad0a2913e65568b1230b5de3947ba7af4a4e448c6f0"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 03c7 3bca 72ed 5f }
		$sequence_1 = { c6025e eb12 c6022f eb0d }
		$sequence_2 = { 8b442430 488d8c2471110000 33d2 41b803010000 }
		$sequence_3 = { 0401 3cbe 8844240b 76e2 }
		$sequence_4 = { 03ce c6840c3801000000 8d8424a05c0000 33f6 }
		$sequence_5 = { 033485c0e54200 c745e401000000 33db 395e08 }
		$sequence_6 = { 488d15d9d20000 488bcb e8???????? 85c0 750a 4883c310 }
		$sequence_7 = { 00686c 42 0023 d18a0688078a }
		$sequence_8 = { 4488a424300d0000 488905???????? e8???????? 4c8d1d5cd40100 498bcc }
		$sequence_9 = { eb62 c6023d eb5d c6025f eb58 c6023a }
		$sequence_10 = { 03c1 1bc9 0bc1 59 e9???????? e8???????? ff742404 }
		$sequence_11 = { 41c1c90d 8bca 4983c201 4403c8 493bc8 }
		$sequence_12 = { 033485c0e54200 8b45e4 8b00 8906 }
		$sequence_13 = { 030495c0e54200 eb05 b8???????? f6400420 }
		$sequence_14 = { 33d2 41b803010000 4488a42470110000 488905???????? e8???????? }
		$sequence_15 = { 3c58 7711 480fbec5 428a8c10507c0200 83e10f eb03 }

	condition:
		7 of them and filesize <434176
}