rule MALPEDIA_Win_Krdownloader_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "5a82ae0a-fad8-52ec-9981-5ad40d1aeb9f"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.krdownloader"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.krdownloader_auto.yar#L1-L120"
		license_url = "N/A"
		logic_hash = "4501a2b9e4a10b142f4eeab904974c078e1ef98420195596ba39d05922e3a30d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { c645e161 c645e22e c645e370 c645e468 c645e570 c645e63f c645e76d }
		$sequence_1 = { 8b4df4 8b09 e8???????? 8945f0 }
		$sequence_2 = { 7528 8b45fc 0345f4 0fb6482c 51 68???????? }
		$sequence_3 = { e8???????? 8945d8 8b4dfc 51 8b55f8 }
		$sequence_4 = { 7418 8b4dec 0fbe11 0fbe45f3 3bd0 }
		$sequence_5 = { 8955f0 8b45f0 8945f8 c745d800000080 817d1000000080 7310 }
		$sequence_6 = { c745f001000000 eb28 837d0c00 7422 6a04 68???????? 8b4d0c }
		$sequence_7 = { 89815c0d0300 8b55fc 8b82500d0300 50 ff15???????? }
		$sequence_8 = { 735e 8b4dfc 8b5134 83ea01 3955f4 }
		$sequence_9 = { 83c001 8945fc 817dfc6f020000 7d63 8b4dfc 8b55f8 }

	condition:
		7 of them and filesize <352256
}