
rule MALPEDIA_Win_Xiangoop_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "bc98151f-3c19-5785-9ae3-c69b23dbc040"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.xiangoop"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.xiangoop_auto.yar#L1-L122"
		license_url = "N/A"
		logic_hash = "94fbd52db4d5481176ad7bfd7bb74c96cb0ad2e3aa8f7b123dd0955d4f95f88c"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { b801000000 d1e0 8b55f4 0fb6440208 25ff000000 }
		$sequence_1 = { c1e903 8d540906 8b4508 8990e0010000 c745ec00000000 8b4d08 }
		$sequence_2 = { ebe3 8b45f0 8b0c85a8b00110 8b45ec 807c082800 }
		$sequence_3 = { c1e008 0bc8 ba01000000 6bc203 8b550c 0fb644020c 25ff000000 }
		$sequence_4 = { 8955c8 6804010000 8d85bcfdffff 50 8b4dc8 }
		$sequence_5 = { 81e2ff000000 b801000000 6bc800 8b4510 8854080c 8b4dec }
		$sequence_6 = { c3 b001 c3 c705????????80a50110 b001 c3 68???????? }
		$sequence_7 = { 8b45fc 8b4dfc 034804 894dfc e9???????? b801000000 8be5 }
		$sequence_8 = { 890c02 8b45ec 83c001 8945ec 837dec08 7502 }
		$sequence_9 = { 8b45f4 83c028 8945f4 ebcb }

	condition:
		7 of them and filesize <246784
}