
rule MALPEDIA_Win_Pwnpos_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "abbe2d0a-a645-5f32-9b7c-0253f67ad1b4"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pwnpos"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.pwnpos_auto.yar#L1-L125"
		license_url = "N/A"
		logic_hash = "7bd328aa33dd14635d4dbb434ca27c66253964455bceaea97af6eb90a2de7f21"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d8dbcf9ffff 3985b4f9ffff 8b85a0f9ffff 7306 8d85a0f9ffff 51 50 }
		$sequence_1 = { 391d???????? 0f84a4000000 8d75d4 e8???????? 68???????? 50 c645fc01 }
		$sequence_2 = { 51 c745fc00000000 ffd3 85c0 7507 e8???????? eb0c }
		$sequence_3 = { 6800400000 8d8c2494000000 51 ff15???????? 85c0 7526 8b8c2498400000 }
		$sequence_4 = { 762a 56 e8???????? 8d0445fc6c4400 8bc8 }
		$sequence_5 = { 89564c 895e44 6a08 b9???????? }
		$sequence_6 = { eb14 807a2100 740a 3935???????? 7302 8bd1 }
		$sequence_7 = { 3d00010000 752d 837c241c00 7626 }
		$sequence_8 = { e9???????? 8d9580f9ffff 52 b801000000 898d84f9ffff 898d88f9ffff 6a02 }
		$sequence_9 = { 8bd1 8b09 eb03 8b4908 80792100 74e6 5f }

	condition:
		7 of them and filesize <638976
}