
rule MALPEDIA_Win_Dorkbot_Ngrbot_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "1046d98a-4609-5bec-b876-b018dbb80d3c"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dorkbot_ngrbot"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.dorkbot_ngrbot_auto.yar#L1-L132"
		license_url = "N/A"
		logic_hash = "bcb266c989d4cc3b19fa74f0744a29c545b0b246dcbae9914be22d057afdb410"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 6a5c 56 e8???????? 8b5d0c 6a5c 53 8bf8 }
		$sequence_1 = { ffd6 33c0 a3???????? a3???????? a3???????? 8b45fc }
		$sequence_2 = { c1e704 8b8f84693a02 48 3bc8 0f8289000000 68???????? 8d45ec }
		$sequence_3 = { 3bc6 751a 8b00 898120100000 8b0a 8bb920100000 56 }
		$sequence_4 = { 8b4508 50 8d8da4fdffff 51 68???????? 8d958cf7ffff 6817060000 }
		$sequence_5 = { 8b15???????? 8b1d???????? 6a08 52 ffd3 6804010000 8906 }
		$sequence_6 = { 0145fc ffd3 8bc8 b8d34d6210 f7e1 c1ea06 }
		$sequence_7 = { 6689462d 83c007 66898638100000 5f 895628 c6462c03 b801000000 }
		$sequence_8 = { 53 8d55d4 52 ffd6 85c0 7fdb 5f }
		$sequence_9 = { 0fb6c9 6880000000 83c202 52 8b5508 f7d9 1bc9 }

	condition:
		7 of them and filesize <638976
}