rule MALPEDIA_Win_Chiser_Client_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "e8afcaec-169c-5519-a609-4458271450b4"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.chiser_client"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.chiser_client_auto.yar#L1-L124"
		license_url = "N/A"
		logic_hash = "3bc0569053961dd359f1e4296146fed96a2d550b29a6ec46396d68a2c22beadc"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 668945b7 488d55b7 488d4dd7 e8???????? b862000000 }
		$sequence_1 = { 488bcb e8???????? b801000000 4883c430 415e 5f }
		$sequence_2 = { e8???????? 488d156f390300 488d4c2420 e8???????? cc 48895c2408 4889742410 }
		$sequence_3 = { ff15???????? 483305???????? 488d15bedf0200 488bcb 488905???????? }
		$sequence_4 = { 894810 48634810 b802000000 48f7e1 48c7c1ffffffff 480f40c1 }
		$sequence_5 = { ff15???????? 8bd8 83f801 0f84c7030000 8bc8 83e902 }
		$sequence_6 = { 4c8d0564070000 eb1e 3d03003000 7509 }
		$sequence_7 = { 488bc8 488d15a48e0100 ff15???????? 4885c0 0f8432030000 488bc8 e8???????? }
		$sequence_8 = { 488944246a 89442472 6689442476 c74424502f006900 c74424546e006400 c744245865007800 c744245c2e006800 }
		$sequence_9 = { 488d1590500200 488d4d20 e8???????? cc 48895d08 4883651000 488b86a8000000 }

	condition:
		7 of them and filesize <714752
}