rule MALPEDIA_Win_Blackmatter_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "08d983f8-89d3-5398-96f5-8f771b0988c8"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.blackmatter"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.blackmatter_auto.yar#L1-L119"
		license_url = "N/A"
		logic_hash = "67609ff5035d7d172ddf1a903ab845a6e5b4b36e758aab3cb262223fbb37577d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 57 c745fc00000000 ff35???????? e8???????? 8bf8 }
		$sequence_1 = { ff75f8 ff15???????? 85c0 0f85e7000000 68???????? }
		$sequence_2 = { 83c4d8 53 56 57 c745fc00000000 c745f800000000 }
		$sequence_3 = { e8???????? 8945fc eb0c 83c702 ff4df8 837df800 }
		$sequence_4 = { e9???????? ff75c8 e8???????? 8945c4 }
		$sequence_5 = { ff15???????? 83c40c 8d047500000000 50 8d45da }
		$sequence_6 = { 85f6 0f842c010000 56 ff35???????? e8???????? ff35???????? e8???????? }
		$sequence_7 = { f7f1 92 3b4508 720b 3b450c }
		$sequence_8 = { 8945ec e8???????? e8???????? 803d????????00 7405 }
		$sequence_9 = { ff75f4 e8???????? 5e 5b 8be5 5d c3 }

	condition:
		7 of them and filesize <194560
}