rule MALPEDIA_Win_Fobber_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ab54349a-7d99-57ef-92f9-d6c817ce7b6a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.fobber"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.fobber_auto.yar#L1-L175"
		license_url = "N/A"
		logic_hash = "16740b1e84557358ab17bd4ccf852daa4c4e1c0339646d5e9060d6d119fab8ab"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 89e5 51 8b4510 8b5508 8b4d0c 3002 c0c803 }
		$sequence_1 = { 89e5 6a00 ff750c ff7508 e8???????? }
		$sequence_2 = { 89e5 31c0 50 50 ff750c ff7508 50 }
		$sequence_3 = { 57 51 8b7d08 30c0 31c9 f7d1 fc }
		$sequence_4 = { e303 4f 89f8 5f 59 }
		$sequence_5 = { 8b750c 8b4d10 39f7 760e 8d0431 39f8 7607 }
		$sequence_6 = { 660fc146f9 6685c0 7515 0fb646f8 50 0fb746f6 }
		$sequence_7 = { 55 89e5 6800800000 6a00 }
		$sequence_8 = { 750f 0fb703 83f861 0f8301fe0000 }
		$sequence_9 = { 57 33714b 8aa07b74cafc 16 aa 5a }
		$sequence_10 = { 7527 e8???????? 83c020 3bf0 0f8434510100 e8???????? }
		$sequence_11 = { 000f 843d???????? 328801008bff 55 8bec ff7514 6a00 }
		$sequence_12 = { c00f84 40 17 0100 8b4d08 83600400 }
		$sequence_13 = { 7706 6205???????? 294a75 f2149c 7674 }
		$sequence_14 = { e8???????? 85f6 0f84fd610100 8b45d4 }
		$sequence_15 = { 7508 e8???????? 59 59 5d c3 53 }

	condition:
		7 of them and filesize <188416
}