
rule MALPEDIA_Win_Nvisospit_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "824469e0-98f2-5eab-b839-ba6db77c2d16"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nvisospit"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.nvisospit_auto.yar#L1-L119"
		license_url = "N/A"
		logic_hash = "385fb86660d71ea6f219554af1885e2ee67e8307dd338d6dbd8b2f326f4be091"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 83f801 0f851e010000 8d710c 81fe???????? 0f8350feffff 895dbc }
		$sequence_1 = { a1???????? ffd0 83ec04 0fb785a2f9ffff 0fb7c0 8d959cf9ffff 89542410 }
		$sequence_2 = { c70424???????? e8???????? 85db c705????????02000000 0f85d1fdffff }
		$sequence_3 = { a1???????? 31c9 c705????????00004000 8b00 85c0 }
		$sequence_4 = { 89442404 c70424???????? e8???????? 0fb785a8f9ffff }
		$sequence_5 = { 0f8e16010000 85d2 0f8493010000 b9???????? 81f9???????? }
		$sequence_6 = { 0fb7c0 8d959cf9ffff 89542410 c744240c00000000 8d958ef9ffff 89542408 }
		$sequence_7 = { 83ec0c 8945bc 8b45bc 89442404 }
		$sequence_8 = { e8???????? c7442404b0feffff c70424???????? e8???????? c7442404ccffffff c70424???????? }
		$sequence_9 = { 8d9dacfbffff 81c307010000 895c2414 8d9dacfbffff 83c306 895c2410 894c240c }

	condition:
		7 of them and filesize <66560
}