rule MALPEDIA_Win_Mespinoza_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "6af67872-bac6-59d0-8e7f-a6515453822a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mespinoza"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.mespinoza_auto.yar#L1-L128"
		license_url = "N/A"
		logic_hash = "b9e1c3335fd9ffa3b60b976c6289b141c236447ff76a5dd17787957756af56c7"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d4d9c e8???????? 83eb01 75e7 8b4d0c }
		$sequence_1 = { 897d0c c645fc01 85ff 7446 56 8bcf e8???????? }
		$sequence_2 = { 8b4dc4 8b7dc0 6aff 6a01 }
		$sequence_3 = { 891f 895f04 6a01 895dfc e8???????? 59 894704 }
		$sequence_4 = { 03c1 3bc1 7334 8bde 8bf1 2bf0 }
		$sequence_5 = { 75f9 2bd6 8db5f8feffff 8d5e01 8a06 46 84c0 }
		$sequence_6 = { 83e03f 6bd030 895de4 8b049d00b04700 8945d4 8955e8 8a5c1029 }
		$sequence_7 = { 8b6c240c 56 57 55 8bf9 e8???????? 8b37 }
		$sequence_8 = { 64a300000000 8965f0 8b7508 8b7d0c 8975ec c745fc00000000 0f1f440000 }
		$sequence_9 = { 8bc3 2bc2 894714 8b7508 8bce e8???????? 84c0 }

	condition:
		7 of them and filesize <1091584
}