rule MALPEDIA_Win_Astralocker_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "0d5879c8-ffd6-54eb-8701-3a0bd5bd2437"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.astralocker"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.astralocker_auto.yar#L1-L121"
		license_url = "N/A"
		logic_hash = "04cf0865e55d3f7d37324f7ff4a5b3ef42183f756ec3ed69d17a248a6814ecfc"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b5508 8b440a04 50 8b0c0a 51 e8???????? }
		$sequence_1 = { 83c102 894dfc 837dfc0a 0f83dc000000 8b55fc 8b4508 }
		$sequence_2 = { 6bc20a 8b4d08 33d2 33f6 891401 }
		$sequence_3 = { 6bc20a 8b4d08 33d2 33f6 }
		$sequence_4 = { 8b440a04 50 8b0c0a 51 e8???????? 83c408 8945ec }
		$sequence_5 = { 894dfc 837dfc0a 0f83dc000000 8b55fc 8b4508 8b4cd004 }
		$sequence_6 = { 8b4508 8b4cd004 51 8b14d0 52 e8???????? }
		$sequence_7 = { 33c0 33f6 89040a 89740a04 }
		$sequence_8 = { ba08000000 6bc20a 8b4d08 33d2 33f6 891401 89740104 }
		$sequence_9 = { 33c0 33f6 89040a 89740a04 c745fc00000000 eb09 }

	condition:
		7 of them and filesize <191488
}