
rule MALPEDIA_Win_Xdspy_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "770ce833-e4ad-5e91-a2e8-e19a8fcb8719"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.xdspy"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.xdspy_auto.yar#L1-L167"
		license_url = "N/A"
		logic_hash = "f9c3ada66244c45df3d3dc2c6a2b3ef1f7e34e7bdca43fe98eeac2240819a0e8"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d45ec 50 ff35???????? e8???????? 83f8ff }
		$sequence_1 = { ffb56cd8ffff 8d8570d8ffff 6800040000 6a01 50 e8???????? }
		$sequence_2 = { 8b36 8bce c1f905 8b0c8d804e4100 }
		$sequence_3 = { ff7580 8b3d???????? ffd7 8d4580 50 68???????? 56 }
		$sequence_4 = { 8d45e0 50 57 8d85e02a0000 50 ff75dc ffd3 }
		$sequence_5 = { 83c414 83c8ff e9???????? 8bc6 c1f805 57 8d3c85804e4100 }
		$sequence_6 = { 8b4de0 8d0c8d804e4100 8901 8305????????20 }
		$sequence_7 = { 8d8510ecffff 57 50 e8???????? ffb56cd8ffff }
		$sequence_8 = { 0f1f4000 660f1f840000000000 420fb68431309b1700 88840db0080000 488d4901 }
		$sequence_9 = { 488b15???????? 488d8da0080000 ffd0 660f6f0d???????? 488d3550331700 }
		$sequence_10 = { c705????????67736666 c705????????6e747764 c705????????73752f65 66c705????????6d6d 488d1563121700 }
		$sequence_11 = { 488d4901 84c0 75e8 80bd400c000000 488d85400c0000 7413 }
		$sequence_12 = { 4883f860 7ccf 488d15f85c1700 488d0d41e60100 4c8d0552e60100 }
		$sequence_13 = { fe08 488d4001 803800 75f5 488d8db0080000 ff15???????? }
		$sequence_14 = { 83f9ff 0f8496010000 ba01000000 448d420f }
		$sequence_15 = { 33c9 ff15???????? 48898424a8000000 660f6f05???????? }

	condition:
		7 of them and filesize <3244032
}