
rule MALPEDIA_Win_Dnspionage_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "80d80ee2-7c3c-5a6f-84fc-982c0a0f58b9"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.dnspionage"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.dnspionage_auto.yar#L1-L118"
		license_url = "N/A"
		logic_hash = "6f236089a9c79217d1f5a567e48544242146a1c819e624fb6aad3710206efaec"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { f7470c00020000 7507 8bc8 e8???????? 894320 85c0 }
		$sequence_1 = { 50 8d45f4 50 6a13 57 }
		$sequence_2 = { 0f1f8000000000 8bc7 8d5001 8a08 40 84c9 75f9 }
		$sequence_3 = { c7450c00000000 8d4d0c ba???????? 51 8d4df4 51 }
		$sequence_4 = { 83f97f 7307 be7f000000 eb11 8bf7 8d4e01 0f1f00 }
		$sequence_5 = { 33f6 397510 762c 8b45f0 }
		$sequence_6 = { 8b4810 e8???????? a3???????? e9???????? }
		$sequence_7 = { 57 8bfa 85f6 0f8487000000 85ff 0f847f000000 }
		$sequence_8 = { 7202 8b12 56 52 8d8518feffff }
		$sequence_9 = { 8bce 8903 83c408 c1e902 }

	condition:
		7 of them and filesize <786432
}