rule MALPEDIA_Win_Chthonic_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "a742c49c-6e3e-5872-bf95-e2e0adb04114"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.chthonic"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.chthonic_auto.yar#L1-L120"
		license_url = "N/A"
		logic_hash = "836fdc80a654c12e0017df0790b315dbe177f1e5fd0fa5cd260efc9eb4af2475"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 7459 4f 8bf0 8bcf d3ee 83e601 }
		$sequence_1 = { 0f845d010000 4f 8bf0 8bcf }
		$sequence_2 = { 81cf00ffffff 47 8a01 8845ff 8d84bdfcfbffff 8b10 }
		$sequence_3 = { 80e17f 8808 b001 5b c3 55 }
		$sequence_4 = { 8b75f8 83fe02 0f850d010000 8b4df0 }
		$sequence_5 = { 016e04 83c703 013e 8b36 83c410 }
		$sequence_6 = { 5e 0f94c0 5b c9 c3 8b041a }
		$sequence_7 = { 53 ff7510 ff7508 e8???????? 85c0 }
		$sequence_8 = { 80e17f 8808 b001 5b c3 55 8bec }
		$sequence_9 = { ff751c ff7518 ff7514 53 ff7510 ff7508 e8???????? }

	condition:
		7 of them and filesize <425984
}