rule MALPEDIA_Win_Neutrino_Pos_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "3a77c0fc-cd49-5986-b2b4-8a8639992c93"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.neutrino_pos"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.neutrino_pos_auto.yar#L1-L127"
		license_url = "N/A"
		logic_hash = "d3da7317997b76876b14e53b428d397cde821604c2c6da81c73b18c8b2dd677f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 68fbd5fba3 43 53 897dfc e8???????? 83c40c 56 }
		$sequence_1 = { 5a 6a71 6689955affffff 5a 6a61 6689955cffffff }
		$sequence_2 = { 6863ad115b 6a04 c745e801000000 8945f4 e8???????? 59 }
		$sequence_3 = { e8???????? 59 59 6a00 56 e9???????? }
		$sequence_4 = { 6a62 66898556ffffff 58 6a53 66898558ffffff }
		$sequence_5 = { 59 6a64 66898d6cffffff 59 6a68 66898d6effffff 59 }
		$sequence_6 = { 6a63 6689854cffffff 58 6a62 6689854effffff 58 6a69 }
		$sequence_7 = { 66895db2 6a64 8bd9 66895db4 8bd8 66895db6 5b }
		$sequence_8 = { 8b45e0 8b08 6a03 50 ff5138 }
		$sequence_9 = { 66894dd6 66894dd8 66894dda 66894ddc 66894dde 66894de0 66894de2 }

	condition:
		7 of them and filesize <188416
}