rule MALPEDIA_Win_Reaver_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "92b8afe7-b0ea-5ba5-8d5f-5512437f6132"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.reaver"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.reaver_auto.yar#L1-L116"
		license_url = "N/A"
		logic_hash = "8a78ae101ee8d9e477556b7d81328c10daa6a32306210d234ed44ad07120f4bd"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ff15???????? 85c0 7453 8d45f4 50 ff7508 }
		$sequence_1 = { 50 ff7508 6a00 ff15???????? 85c0 7440 }
		$sequence_2 = { ff15???????? 85c0 7453 8d45f4 }
		$sequence_3 = { 85c0 7453 8d45f4 50 ff7508 }
		$sequence_4 = { 85c0 7440 8b45f4 6a00 8945e8 }
		$sequence_5 = { 85c0 7440 8b45f4 6a00 }
		$sequence_6 = { 85c0 740d ff15???????? 3d14050000 7504 33c0 }
		$sequence_7 = { 8bec 83ec1c 8d45fc 50 68ff010f00 }
		$sequence_8 = { 8bec 83ec1c 8d45fc 50 68ff010f00 ff15???????? 50 }
		$sequence_9 = { 85c0 740d ff15???????? 3d14050000 }

	condition:
		7 of them and filesize <106496
}