rule MALPEDIA_Win_Common_Magic_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "51a78d88-2ba4-5106-aa0c-c758f14020ef"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.common_magic"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.common_magic_auto.yar#L1-L118"
		license_url = "N/A"
		logic_hash = "b14e276c951448d5c194fa4cd51d59dbec4eb8aa1757a9205bc8d8e9186ff3cd"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d049d78824100 8b30 8945fc 90 }
		$sequence_1 = { 03c0 eb3c 8bd1 b8feffff7f d1ea 2bc2 }
		$sequence_2 = { c78578ffffff00000000 c7857cffffff00000000 8d9574ffffff c645fc09 8d8d84feffff }
		$sequence_3 = { 6689855cffffff b8feffff7f 2bc1 c7856cffffff00000000 c78570ffffff07000000 }
		$sequence_4 = { 33c9 8bc1 3914c5e84a4100 7408 }
		$sequence_5 = { c7459c65007800 c745a065000000 83f817 0f82140c0000 83bd58ffffff08 8d8544ffffff }
		$sequence_6 = { 51 50 51 ffb580feffff 8d8d5cffffff }
		$sequence_7 = { 51 ffb580feffff 8d8d5cffffff e8???????? 838d78feffff06 8d8de4feffff 83bdf8feffff08 }
		$sequence_8 = { 8b0c8570804100 8a043b 03ce 8b75dc 03cb 43 }
		$sequence_9 = { 2bc2 3bc8 760e b8ffffff7f befeffff7f 03c0 }

	condition:
		7 of them and filesize <212992
}