
rule MALPEDIA_Win_Shakti_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "535cf33d-f06d-5859-b025-0ff160716ffb"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.shakti"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.shakti_auto.yar#L1-L172"
		license_url = "N/A"
		logic_hash = "6f5489cc7281ed05aa1395fcaba968324612a285b4f1d07b39699fdb3c984697"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8945ec 8b4dd4 83c102 894dd4 e9???????? 8b55c0 }
		$sequence_1 = { 0fb711 81fa4d5a0000 752e 8b45c0 8b483c }
		$sequence_2 = { 8b45fc 8b4dd8 0308 894df0 8b55fc }
		$sequence_3 = { 0fb7c2 83f801 753d b9ff0f0000 8b55f0 66230a 0fb7c1 }
		$sequence_4 = { 8b45c0 03423c 8945f8 6a40 }
		$sequence_5 = { 52 6a00 ff55e4 8945d8 8b45f8 8b4854 894de0 }
		$sequence_6 = { 8b45e0 8b0c10 034dc0 baff0f0000 8b45f0 }
		$sequence_7 = { 8b55f8 0355c0 8955f8 8b45f8 }
		$sequence_8 = { 8b742408 85f6 741e 803e00 7512 ff760c e8???????? }
		$sequence_9 = { ff34c5b4a24000 53 57 e8???????? 83c40c 85c0 }
		$sequence_10 = { 50 ff759c ff15???????? 85c0 740d 837d9000 }
		$sequence_11 = { 8bff 55 8bec 8b4508 33c9 3b04cd10a04000 7413 }
		$sequence_12 = { ff15???????? 89459c 83f8ff 7507 32c0 e9???????? 57 }
		$sequence_13 = { bf04010000 57 8d860e080000 50 6a00 }
		$sequence_14 = { 6a08 50 890d???????? ff15???????? }
		$sequence_15 = { 837dd400 a1???????? 7423 c700b8000000 a1???????? }

	condition:
		7 of them and filesize <191488
}