
rule MALPEDIA_Win_Logtu_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "c67bd86c-2bf9-53d0-9e56-6b46a7295f73"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.logtu"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.logtu_auto.yar#L1-L118"
		license_url = "N/A"
		logic_hash = "a1a55d055cae44fc8e92b272f8aaf6bf080cbc3cc39bc731b57992d62cbc8c84"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8bf0 8d85a4fdffff 68???????? 50 ff15???????? }
		$sequence_1 = { ff15???????? 8d8534ffffff 50 ff15???????? 6a01 }
		$sequence_2 = { 50 6a64 6a00 ff15???????? 85c0 7509 8b45bc }
		$sequence_3 = { 8bec 81ec98050000 a1???????? 33c5 8945fc 53 }
		$sequence_4 = { 55 8bec 81ec98050000 a1???????? 33c5 8945fc 53 }
		$sequence_5 = { 8d8574faffff 50 8d8534ffffff 50 }
		$sequence_6 = { 50 8d85fcf7ffff 68???????? 50 e8???????? 8d85fcf7ffff 6800040000 }
		$sequence_7 = { 6a01 8bf0 8d85a4fdffff 68???????? }
		$sequence_8 = { 8d8584faffff 50 8d8574faffff 50 8d8534ffffff }
		$sequence_9 = { 8d8578faffff 50 8d8584faffff 50 }

	condition:
		7 of them and filesize <924672
}