rule MALPEDIA_Win_Karius_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ed0a7186-5551-553c-ac59-b131d3af72d8"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.karius"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.karius_auto.yar#L1-L249"
		license_url = "N/A"
		logic_hash = "b146425f067402ca1aeb5e04aa4caed2d124eb5c4ba40f66c5f112d8e9115a94"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 4c8b8424a0000000 bf01000000 8bd7 498bce ffd3 4183bf8c00000000 }
		$sequence_1 = { 4d03d6 448bcd 85db 0f8477000000 8bb424b0000000 }
		$sequence_2 = { 0f84b3000000 458b9f88000000 4d03de 418b5b18 85db }
		$sequence_3 = { ffd3 4183bf8c00000000 0f84b3000000 458b9f88000000 }
		$sequence_4 = { 488b05???????? 4885c0 7512 ff15???????? 488905???????? }
		$sequence_5 = { 8bb424b0000000 418b10 8bcd 4903d6 0fb602 }
		$sequence_6 = { c3 85c0 7505 e8???????? b801000000 }
		$sequence_7 = { 85db 0f849d000000 41837b1400 0f8492000000 }
		$sequence_8 = { 0f8492000000 458b4320 458b5324 33ed 4d03c6 4d03d6 }
		$sequence_9 = { 8d7b01 448bfb 448be3 4885c9 }
		$sequence_10 = { 56 be???????? 33d2 8a040a 3a06 7522 }
		$sequence_11 = { 83e830 89450c db450c 8a07 d9ca d8c9 }
		$sequence_12 = { b801000000 8702 83f801 74f4 }
		$sequence_13 = { 752c 8a4701 3c30 7c25 3c39 }
		$sequence_14 = { 488d4b10 488d542450 41b804000000 c6430f68 }
		$sequence_15 = { 4d8bcf 33d2 41b800001000 488bce }
		$sequence_16 = { 803e5d 7508 5f 5b 8d4601 5e }
		$sequence_17 = { 7505 8d7b02 eb09 6685c0 }
		$sequence_18 = { 8d7308 56 ffd7 50 56 e8???????? }
		$sequence_19 = { ff15???????? 4c8be8 498bce ff15???????? 4d85ed }
		$sequence_20 = { 8b4dfc 83c404 8945f4 83c706 050024ffff }
		$sequence_21 = { 4d8bc7 488bd0 488bce ff15???????? }
		$sequence_22 = { e9???????? 8b45f8 5f 5b 5e }
		$sequence_23 = { 8b4508 85c0 7417 8b4008 85c0 7412 8b4d0c }
		$sequence_24 = { 7405 f60001 7502 33c0 }
		$sequence_25 = { 448bc0 33d2 488bce ff15???????? 4c8bf0 4885c0 }
		$sequence_26 = { 48895c2420 4d8bcc 4d8bc7 488bd0 }

	condition:
		7 of them and filesize <434176
}