
rule MALPEDIA_Win_Carrotbat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "b4eb53a6-f964-58c0-a140-244bef4847cc"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.carrotbat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.carrotbat_auto.yar#L1-L121"
		license_url = "N/A"
		logic_hash = "c457876e0174827e0c750e3be442dfc99dddf6a42b624668fe26e525a3bccc83"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b7c2404 66c1c60c 8b742408 f6d7 33cd f7d3 }
		$sequence_1 = { 8f442434 51 887c2404 66890424 890424 }
		$sequence_2 = { 8b0c8d20ee4000 8d440104 8020fe ff36 e8???????? 59 }
		$sequence_3 = { c3 8bff 56 57 33f6 bf???????? 833cf5a4d5400001 }
		$sequence_4 = { 8b0c8d20ee4000 c1e006 8d440104 8020fe ff36 }
		$sequence_5 = { c1f805 8d3c8520ee4000 8bf3 83e61f c1e606 8b07 0fbe440604 }
		$sequence_6 = { 888c05f4fdffff 40 84c9 75ed 8d85f8feffff 6a5c }
		$sequence_7 = { 50 66a5 ff15???????? 6810270000 ff15???????? }
		$sequence_8 = { 5b c21000 ff25???????? c705????????6ca14000 }
		$sequence_9 = { 8f442434 9c 57 ff74243c c24000 686d3f4f6e }

	condition:
		7 of them and filesize <360448
}