rule MALPEDIA_Win_Bid_Ransomware_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "123f6d77-eca2-5400-ac56-e3f30e76b796"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bid_ransomware"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.bid_ransomware_auto.yar#L1-L114"
		license_url = "N/A"
		logic_hash = "040b1903110ce367e4f39e634882ebba58d8e30bf0983ec0eaeaeca56a956f74"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { c705????????20202020 68???????? 50 e8???????? }
		$sequence_1 = { 6a00 e8???????? ff75fc e8???????? c9 c3 }
		$sequence_2 = { ff75b0 e8???????? ff75b0 e8???????? 6800800000 ff75a8 }
		$sequence_3 = { 55 8bec 83c4f4 6800800000 6a40 }
		$sequence_4 = { 881f 83c701 83f800 77e3 eb0e }
		$sequence_5 = { 8b4d08 80c141 c745c05c5c3f5c 884dc4 c745c53a5c2a2e }
		$sequence_6 = { 53 6a00 6a00 6a00 ff75e4 e8???????? }
		$sequence_7 = { 8945f0 eb15 ff75f4 e8???????? }
		$sequence_8 = { 68ea030000 ff35???????? e8???????? 8945fc }
		$sequence_9 = { e8???????? 8b85acfdffff 83e001 7414 8b7508 }

	condition:
		7 of them and filesize <57344
}