rule MALPEDIA_Win_Nightsky_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "8aa7bf90-2e66-55fa-ac44-1eeed72fb6ec"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.nightsky"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.nightsky_auto.yar#L1-L124"
		license_url = "N/A"
		logic_hash = "e63cd2d4ab9373a42087ae988b3e3adac99eadab50dc02b0732a77e7f3626d28"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 420fb68c1210ab0400 c1e108 0bc8 420fb6841212ab0400 }
		$sequence_1 = { 4150 4d0fabe0 66442bc5 311424 6641d3e0 4158 4863d2 }
		$sequence_2 = { 4883ec48 488364243000 8364242800 41b803000000 488d0dc0460000 4533c9 ba00000040 }
		$sequence_3 = { 5f c3 488d05cf110000 48b90000000000000080 488987c8000000 488d0557990200 }
		$sequence_4 = { e8???????? 488d15d92c0100 41b804010000 33c9 c605????????00 ff15???????? }
		$sequence_5 = { 488d15d4be0000 41b898000000 498bd9 e8???????? 488b8424d0050000 488b9424e8050000 }
		$sequence_6 = { e41d 1a5b5f a9b7f95f5f b8cbaa75cc d113 0ae4 }
		$sequence_7 = { 0f8c96000000 3b1d???????? 0f838a000000 488bf3 4c8be3 49c1fc05 4c8d2d7e190100 }
		$sequence_8 = { 488d0d0fda0000 480f45cf 48894b48 e8???????? eb17 4885ff 488d0dead90000 }
		$sequence_9 = { 4883ec28 4c8bc1 4c8d0d52bbfdff 498bc9 }

	condition:
		7 of them and filesize <19536896
}