rule MALPEDIA_Win_Unidentified_105_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "80a8f5ec-0d23-5074-b907-8dcd99006ffb"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_105"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.unidentified_105_auto.yar#L1-L114"
		license_url = "N/A"
		logic_hash = "03b63f792ccab1aa0e70284622fef7dcf74ab6cde5a0b9206fdbab8d689a2bd1"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 85c0 0f95c0 84c0 742c }
		$sequence_1 = { 8bf8 8d4f02 b856555555 f7e9 8bc2 c1e81f 03c2 }
		$sequence_2 = { 6a00 8d8dd0feffff 51 8d95fcfeffff }
		$sequence_3 = { 8d8d94feffff 51 6800000010 50 52 ff15???????? 85c0 }
		$sequence_4 = { e8???????? 83c404 50 e8???????? a1???????? 6800020000 }
		$sequence_5 = { 83f8ff 7459 8d9424a0010000 52 }
		$sequence_6 = { 68???????? 56 e8???????? 8bc6 83c454 }
		$sequence_7 = { 8bf8 8d4f02 b856555555 f7e9 8bc2 }
		$sequence_8 = { 8b3d???????? 8d45e4 50 33f6 }
		$sequence_9 = { 6800100000 8d85f8efffff 50 51 }

	condition:
		7 of them and filesize <253952
}