rule MALPEDIA_Win_Racket_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "7cb28a65-c30c-589f-a924-680f6f853124"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.racket"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.racket_auto.yar#L1-L133"
		license_url = "N/A"
		logic_hash = "d1589a59b0768c1bd03360a8449d283c6a3783d8d4ace18ebd09610946148618"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ffd3 8b8eec000000 8bf8 8b1d???????? 8d45ec 57 50 }
		$sequence_1 = { 807d0800 743b e8???????? 6a00 ff7604 6845090000 ff35???????? }
		$sequence_2 = { 57 0f1f840000000000 8bc1 c745fc02000000 2bc2 8dbb78fdffff 81c680fdffff }
		$sequence_3 = { 0f44c1 50 ff75f4 8b473c 68a2090000 ff34856cb30610 ff15???????? }
		$sequence_4 = { 40 50 68???????? 6aff 8d85fcfdffff 6800010000 50 }
		$sequence_5 = { 0f8433020000 833d????????00 0f8426020000 833d????????00 0f8419020000 833d????????00 0f840c020000 }
		$sequence_6 = { 83c430 3945cc 8b45b8 7501 40 8b4dc0 }
		$sequence_7 = { 8b4e04 85c9 7537 8b4510 8b7838 85ff 7e75 }
		$sequence_8 = { ff740e08 68ac080000 ff35???????? ff15???????? 83c420 2bd8 7418 }
		$sequence_9 = { 6a00 68d6070000 897ddc ff34856cb30610 8975d0 ff15???????? 83c410 }

	condition:
		7 of them and filesize <985088
}