rule MALPEDIA_Win_Pikabot_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "16fbebe5-029d-50d1-a8a8-9f8a45a24f27"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pikabot"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.pikabot_auto.yar#L1-L175"
		license_url = "N/A"
		logic_hash = "81c8e73356106864f0a8f72d23108459a17754dd4d587aefd7feb43e822dba1f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8945f8 8b4510 8945f4 8b4510 48 }
		$sequence_1 = { 894510 837df400 741a 8b45fc 8b4df8 8a09 }
		$sequence_2 = { 8b4df8 8a09 8808 8b45fc }
		$sequence_3 = { 40 8945fc 8b45f8 40 8945f8 ebd3 8b4508 }
		$sequence_4 = { 8945f8 ebd3 8b4508 c9 c3 55 }
		$sequence_5 = { 83ec0c 8b4508 8945fc 8b450c 8945f8 8b4510 }
		$sequence_6 = { 7ce9 8b4214 2b420c 5f }
		$sequence_7 = { e8???????? ffd0 c9 c3 55 8bec }
		$sequence_8 = { 8bfa 85c9 7436 85ff }
		$sequence_9 = { 8b0cba 03ce e8???????? 8bd0 }
		$sequence_10 = { 8a1c08 8d4320 0fb6c8 8d53bf 80fa19 }
		$sequence_11 = { 40 8945fc 3bc7 72d5 }
		$sequence_12 = { 55 8bec 83ec10 53 56 8b35???????? b84d5a0000 }
		$sequence_13 = { e8???????? 8bd0 e8???????? 3b45fc }
		$sequence_14 = { c3 56 8bf1 85c9 7419 85d2 7415 }
		$sequence_15 = { 84c0 75f6 c60100 8bc6 5e }
		$sequence_16 = { c9 c3 64a130000000 8b4018 c3 55 }

	condition:
		7 of them and filesize <1717248
}