rule MALPEDIA_Win_Hancitor_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "e94e88e2-da44-5855-8e98-8220d615aa1e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.hancitor"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.hancitor_auto.yar#L1-L234"
		license_url = "N/A"
		logic_hash = "3fe1f27a710b2ccfc55ec6a2163075344a7f89cf27a8c741d778d1b9ea2b6391"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 6a00 6824040000 6a00 6a00 6a00 }
		$sequence_1 = { 6800010000 6a40 68???????? e8???????? }
		$sequence_2 = { 8bec a1???????? 85c0 740c ff7508 6a00 50 }
		$sequence_3 = { 8bec 8b4d08 6a00 6a01 51 }
		$sequence_4 = { 68???????? ff7508 c605????????00 ff15???????? }
		$sequence_5 = { a3???????? 85c0 7502 5d c3 ff7508 6a00 }
		$sequence_6 = { 8b4df4 51 8b55f8 52 8b4510 }
		$sequence_7 = { 8b4d08 0fbe11 83fa7d 750e }
		$sequence_8 = { 8bd8 83fbff 7509 6a00 57 }
		$sequence_9 = { 6a00 6a01 8b5508 52 ff55f4 33c0 8be5 }
		$sequence_10 = { 8b4df4 8b5104 83ea08 d1ea 8955d4 }
		$sequence_11 = { c60600 ff15???????? 8b3d???????? 85c0 740a }
		$sequence_12 = { 8b4dec 8b55f4 035128 8b4518 8910 eb02 }
		$sequence_13 = { 8945f8 8b4df8 894df4 6a00 6a01 }
		$sequence_14 = { 7411 8d85f4fdffff 50 8b4d08 51 }
		$sequence_15 = { 8b4d08 53 56 57 8b413c }
		$sequence_16 = { 8945cc 8365e400 c745bc0a000000 eb07 8b45bc }
		$sequence_17 = { c3 4b fd 008d4556f400 08640f08 ed fec3 }
		$sequence_18 = { a1???????? 8945b4 a1???????? 83c044 a3???????? 8b45b4 83e803 }
		$sequence_19 = { b9382baa99 c7458ce4f25701 ff15???????? 894da0 a1???????? }
		$sequence_20 = { 6a00 6a00 ff15???????? c745a064000000 }
		$sequence_21 = { c645f300 c645fc65 c645fd00 c745f8dc030000 8365b800 }
		$sequence_22 = { 8945dc e9???????? b9382baa99 c745f464000000 }
		$sequence_23 = { 0f8482000000 c645f301 0fb645f3 85c0 7476 a1???????? 83c044 }

	condition:
		7 of them and filesize <106496
}