rule MALPEDIA_Win_Terminator_Rat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "9d4805e3-697a-5809-9888-0af99434fee9"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.terminator_rat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.terminator_rat_auto.yar#L1-L113"
		license_url = "N/A"
		logic_hash = "460088279758b4b56f7253332ea9c90ec016fa5d0376dce042f468a189f77f7d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ffb519010000 8947fc 8b47f4 8b4008 894708 e8???????? 8b47fc }
		$sequence_1 = { c70020000000 8b852d010000 2b08 894804 }
		$sequence_2 = { 33db 395e0c 752f 6a40 6800100000 6800180000 }
		$sequence_3 = { 26a130000000 07 8b400c 8b701c }
		$sequence_4 = { 50 ffb525010000 ff95e1000000 85c0 }
		$sequence_5 = { eb31 ff9509010000 3d4c270000 750e }
		$sequence_6 = { 57 8bfc 81ec04040000 53 56 33db }
		$sequence_7 = { 8b4b0c ac 3459 c0c803 3448 c0c803 }
		$sequence_8 = { ffb519010000 8947fc 8b47f4 8b4008 }
		$sequence_9 = { 60 33c0 8b4f0c 8b7f08 }

	condition:
		7 of them and filesize <73728
}