rule MALPEDIA_Win_Unidentified_087_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "40b9cd18-d110-5435-969b-5dfac9c340c4"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.unidentified_087"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.unidentified_087_auto.yar#L1-L174"
		license_url = "N/A"
		logic_hash = "110739d44f9e53e4e50b40a1961bcb5043ade07265d58318b1d26ddc3eb75b3c"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { c7453802000000 ff15???????? 83f801 7409 83f80d 0f8581000000 }
		$sequence_1 = { 4c8d9c2480020000 498b5b28 498b7330 498be3 415c }
		$sequence_2 = { 4d8bcf 4533c0 488d542428 488d4c2450 e8???????? 488d5580 488d4c2450 }
		$sequence_3 = { 895c2420 48895908 4c8bf1 488948c8 }
		$sequence_4 = { 40b601 488bcb ff15???????? 400fb6c6 }
		$sequence_5 = { ff15???????? 483905???????? 752b 8b442460 3905???????? 751f }
		$sequence_6 = { eb09 488b05???????? 33d2 8d3c10 488b4c2450 48634104 f644046006 }
		$sequence_7 = { 488d68a1 4881ece0000000 48c745c7feffffff 48895810 48897818 488b05???????? 4833c4 }
		$sequence_8 = { c6864b01000043 c7466870040210 6a0d e8???????? 59 8365fc00 ff7668 }
		$sequence_9 = { 89430c 8d4310 8d89a4080210 5a 668b31 }
		$sequence_10 = { 6a10 57 ff15???????? 6a00 6a00 6a00 8d8584feffff }
		$sequence_11 = { c745e40f000000 895de0 885dd0 8d45d0 50 }
		$sequence_12 = { ff15???????? 50 8dbdf8feffff e8???????? 83c404 5f }
		$sequence_13 = { c705????????25ca0010 8935???????? a3???????? ff15???????? a3???????? 83f8ff }
		$sequence_14 = { 7461 8d0cbd602c0210 8901 8305????????20 8b11 }
		$sequence_15 = { 85c9 7410 8b14b8 8911 8b0d???????? }

	condition:
		7 of them and filesize <462848
}