rule MALPEDIA_Win_Deadwood_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "5f00cc5a-9602-50e1-9261-d675303486e9"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.deadwood"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.deadwood_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "ea97d4cccc4d6a9b5e482bbc380fcc6fbef419bedaf1f051b13240e62ed24277"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 51 e8???????? 83c404 33db be0f000000 89b42418010000 899c2414010000 }
		$sequence_1 = { 7303 8d4508 8b5518 52 50 8b4110 50 }
		$sequence_2 = { 7464 8bf0 8b4814 894c2424 3bcb 7504 895c2428 }
		$sequence_3 = { 6a01 8d442414 50 8d4c243c 897c247c c744241878f44500 e8???????? }
		$sequence_4 = { 8bf8 85ff 0f8484000000 53 53 53 53 }
		$sequence_5 = { ff15???????? 6804010000 8d8df4fdffff 51 50 ff15???????? 33d2 }
		$sequence_6 = { e8???????? 8b542460 c7442440e4ba4500 bb???????? 895c2454 8b4204 c7440460c8ba4500 }
		$sequence_7 = { 8b07 8b4804 837c390c00 0f94c1 884dd8 c745fc01000000 84c9 }
		$sequence_8 = { 74ed 89450c 8b13 807a1d00 7404 8b3e eb13 }
		$sequence_9 = { 8bb510ffffff e9???????? c3 8d8d34ffffff e9???????? 8d8d18ffffff e9???????? }

	condition:
		7 of them and filesize <1055744
}