rule MALPEDIA_Win_Urausy_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "42f215cc-3fcb-5d25-8a29-1c5fcfaf0e92"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.urausy"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.urausy_auto.yar#L1-L120"
		license_url = "N/A"
		logic_hash = "4f1d0bce8598e73699b4a743f6a21ef45b27ed44d43ef0837b1c95c90d3c9c6b"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 6a00 68???????? 68???????? ff7508 e8???????? 6a00 ff35???????? }
		$sequence_1 = { 8bd3 81c2a5000000 50 53 52 51 }
		$sequence_2 = { ff75e4 e8???????? 8945e8 ff35???????? }
		$sequence_3 = { 6a01 ff35???????? e8???????? 6a00 68???????? 68???????? }
		$sequence_4 = { c21000 55 8bec 81c4ecefffff }
		$sequence_5 = { 0f8585000000 6814000000 68???????? 6a04 8d8500fcffff 50 e8???????? }
		$sequence_6 = { 8d85dcf7ffff 50 57 56 }
		$sequence_7 = { 833d????????00 0f8fae050000 c705????????01000000 ff35???????? 8f45f0 ff35???????? 8f45f4 }
		$sequence_8 = { e8???????? ff75fc e8???????? 8b45f8 c9 c20400 ff25???????? }
		$sequence_9 = { e8???????? b800000000 c9 c21400 }

	condition:
		7 of them and filesize <98304
}