
rule MALPEDIA_Win_Predator_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "139b7e6c-7d6f-5725-bc06-83e05af2728a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.predator"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.predator_auto.yar#L1-L122"
		license_url = "N/A"
		logic_hash = "4f1faf378ed80607ad7505f3b525c8d2a5bbf8d81c1cadcdd453ab7a1d609878"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 55 8bec 83ec18 8bc2 56 8bf1 8d4dfd }
		$sequence_1 = { 80c230 8811 85c0 75f2 51 8d45fd }
		$sequence_2 = { 8d4dfd 57 6a0a 5f 85c0 7916 }
		$sequence_3 = { 03c2 8bce 50 e8???????? 5f 8bc6 5e }
		$sequence_4 = { 7508 83c8ff e9???????? ff75ec e8???????? }
		$sequence_5 = { 83ec18 8bc2 56 8bf1 8d4dfd }
		$sequence_6 = { ff75ec e8???????? 59 8bf0 }
		$sequence_7 = { 7508 83c8ff e9???????? ff75ec e8???????? 59 8bf0 }
		$sequence_8 = { 894e08 89560c 834dfcff 8b4df4 64890d00000000 5f 5e }
		$sequence_9 = { 8b00 57 03c2 8bce }

	condition:
		7 of them and filesize <2211840
}