
rule MALPEDIA_Win_Zeoticus_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "c2a18f25-bc43-5657-ba7f-277a7d143bb2"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.zeoticus"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.zeoticus_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "a4d1e69467730f44a44fc31899a04b37f3c67c9d35561598e18a4009fa030896"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { b901000000 8b442404 0f44f1 85c0 7407 50 ff15???????? }
		$sequence_1 = { 6a00 6a02 6a01 6a00 6a00 6a00 6890010000 }
		$sequence_2 = { 53 68???????? 50 89048d00574300 ff15???????? a1???????? 83c410 }
		$sequence_3 = { 8b0d???????? 8d442420 6a00 6a00 6a00 6a25 6800800000 }
		$sequence_4 = { 8d4c2430 6a18 51 ffd0 a1???????? 83c408 85c0 }
		$sequence_5 = { 42 88440e14 8b4c2424 41 894c2424 83fa0b }
		$sequence_6 = { 56 57 8b7c2414 894c2418 390f 0f86df010000 }
		$sequence_7 = { a3???????? c705????????00000000 c705????????00000000 c705????????00000000 e8???????? 8b4c2408 8b542404 }
		$sequence_8 = { 56 57 894c2410 8b7810 8bf7 90 }
		$sequence_9 = { 83c408 a3???????? ff742420 ffd0 85c0 754a }

	condition:
		7 of them and filesize <468992
}