rule MALPEDIA_Win_Uacme_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "f5c3a5f2-a252-5543-b1be-134e5f419833"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.uacme"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.uacme_auto.yar#L1-L125"
		license_url = "N/A"
		logic_hash = "9cc750a1f13cae79bcf2cd2e379aedeb4cbdf45f9813c77d239c596ff07109f6"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ba???????? e8???????? 8d8df0fbffff e8???????? 8bf8 85ff 741b }
		$sequence_1 = { ff9620060000 33c0 5e 8be5 5d c20400 }
		$sequence_2 = { eb23 8b4d08 e8???????? 03c0 }
		$sequence_3 = { 8d45d8 50 6804900000 56 ff15???????? 6808700000 56 }
		$sequence_4 = { ba???????? 8d8940040000 e8???????? 8b45fc ff7010 ffd6 }
		$sequence_5 = { 8bd8 85db 74d3 8b5508 8bcb e8???????? }
		$sequence_6 = { 668974242e ff15???????? 85c0 0f88c9040000 ff15???????? b940040000 }
		$sequence_7 = { e8???????? 8bce 8d85e0fbffff 8818 40 83e901 }
		$sequence_8 = { b9???????? e8???????? 6683bdf0fbffff00 8bf0 740d 8d85f0fbffff 50 }
		$sequence_9 = { 8d85f0fbffff 50 8d85e0f7ffff 50 e8???????? 8bd8 }

	condition:
		7 of them and filesize <565248
}