rule MALPEDIA_Win_Gold_Dragon_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "eec5e3d6-5655-50ac-8840-a288ffff9f65"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gold_dragon"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.gold_dragon_auto.yar#L1-L117"
		license_url = "N/A"
		logic_hash = "eed1b3c473c88d18a03100aac4bac22cf30de04dad45247c9c63eb23fa6434a1"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? 8bc6 83e61f c1f805 59 8b048500954000 8d0cf6 }
		$sequence_1 = { 85c0 a3???????? 0f848d030000 8b15???????? 68???????? }
		$sequence_2 = { 0fb6fa 3bc7 7714 8b55fc 8a9200844000 }
		$sequence_3 = { a3???????? 0f842d040000 8b15???????? 68???????? }
		$sequence_4 = { a3???????? 0f8422030000 a1???????? 68???????? 50 ffd6 }
		$sequence_5 = { 8b7d08 8d054c914000 83780800 753b b0ff }
		$sequence_6 = { 8db60c844000 bf???????? a5 a5 59 }
		$sequence_7 = { ffd6 85c0 a3???????? 0f84a2050000 }
		$sequence_8 = { ffd6 85c0 a3???????? 0f84ef010000 68???????? ffd7 }
		$sequence_9 = { 85c0 a3???????? 0f8424020000 8b15???????? 68???????? 52 }

	condition:
		7 of them and filesize <90112
}