
rule MALPEDIA_Win_Termite_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "f52e0f9c-00a2-57d7-aba9-0dbbb1d1c2e2"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.termite"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.termite_auto.yar#L1-L131"
		license_url = "N/A"
		logic_hash = "cc787c4fe1eac82cec1ddbf65768a64c7a8c2c3d8dd4b766767f73077448495f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b4508 c1e003 89c2 c1e206 01d0 05???????? 8d5004 }
		$sequence_1 = { e8???????? c744240814000000 8d45dc 89442404 8b45f4 890424 }
		$sequence_2 = { c744241cffffffff c74424188cd44000 c7442414ffffffff 8b4510 89442410 8b450c 8944240c }
		$sequence_3 = { 837dfc00 75d7 b800000000 c9 c3 55 }
		$sequence_4 = { 8b10 a1???????? 8b4d08 894c2408 89542404 890424 e8???????? }
		$sequence_5 = { e8???????? 83f814 7706 837d1400 7f0a b8ffffffff }
		$sequence_6 = { 837d0c00 750a b800000000 e9???????? 8b450c 8b4010 8945f0 }
		$sequence_7 = { 89442404 8b45f0 890424 e8???????? c70424???????? e8???????? 8b45f4 }
		$sequence_8 = { c704240a000000 e8???????? eb0a c745f401000000 eb08 90 c745f400000000 }
		$sequence_9 = { 83ec04 89442404 8d85b4feffff 890424 e8???????? 8d85b4feffff 89442404 }

	condition:
		7 of them and filesize <312320
}