rule MALPEDIA_Win_Mailto_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ea0d0ed3-d3ad-5738-b388-39bdea82080a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.mailto"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.mailto_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "f253c860f2dfd876ea6c63e66e3d4bfe3e95a5b5178079f30b977b373576f89e"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 47 3bfb 7297 8b44241c 8930 8b442420 85c0 }
		$sequence_1 = { 83c404 85f6 7429 85ed 7419 8b742414 }
		$sequence_2 = { 8b442418 8938 8b44241c 85c0 7402 8930 }
		$sequence_3 = { 55 56 57 8b7c2424 c744241400000000 85ff 7457 }
		$sequence_4 = { 85f6 0f8477010000 e8???????? 3b7014 0f8469010000 8b0d???????? 85c9 }
		$sequence_5 = { 8b08 ff5130 85c0 7822 ff74242c e8???????? }
		$sequence_6 = { 897c242c 8bc8 89442420 c1f81a c1f91f 23c8 8bc1 }
		$sequence_7 = { 40 eb64 83ff01 7522 0fb6d1 bf02000000 83e203 }
		$sequence_8 = { 0fb6466b 884118 0fb6466f 88411c 0fb64652 884101 0fb64656 }
		$sequence_9 = { 0f84ef000000 6a20 e8???????? 83c404 89442410 85c0 }

	condition:
		7 of them and filesize <180224
}