
rule MALPEDIA_Win_Oddjob_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "05ff5b48-0b07-5c37-b3fa-78979fc46d1b"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.oddjob"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.oddjob_auto.yar#L1-L124"
		license_url = "N/A"
		logic_hash = "cba635f9b22031c02deb6504fbb70476906689529cb50c775ead5481738df2df"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? 59 8d9530ffffff 6a01 8bcb 8bc2 }
		$sequence_1 = { c68552fbffff43 c68553fbffff5e c68554fbffff5b c68555fbffff8b c68556fbffff4b }
		$sequence_2 = { 663d3600 751f 66837f0234 7518 }
		$sequence_3 = { 50 bf???????? 57 6a04 53 68???????? ffd6 }
		$sequence_4 = { 8bc3 4b 85c0 0f8498000000 0fb7c1 83f841 7c05 }
		$sequence_5 = { c68596faffff24 c68597faffff08 c68598faffff8b c68599faffff43 }
		$sequence_6 = { c685f8f9ffff40 c685f9f9ffff68 889dfaf9ffff c685fbf9ffff10 889dfcf9ffff 889dfdf9ffff c685fef9ffff51 }
		$sequence_7 = { 889d12f8ffff 889d13f8ffff 889d14f8ffff 889d15f8ffff 889d16f8ffff 889d17f8ffff 889d18f8ffff }
		$sequence_8 = { 85c0 7503 897dfc 397de8 7409 ff75e8 ff15???????? }
		$sequence_9 = { 53 68???????? ffd6 85c0 741c 8d85a094ffff }

	condition:
		7 of them and filesize <221184
}