rule MALPEDIA_Win_Soundbite_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "080e0f3d-446d-56c0-ac80-bd020f7550e1"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.soundbite"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.soundbite_auto.yar#L1-L126"
		license_url = "N/A"
		logic_hash = "dd4f6a00eb49b6e49c1bd5e71a528f06fe40aa9dfa91442cca75ad1ce88ee58a"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b5518 48 89451c 8b4a08 3bc8 7702 2bc1 }
		$sequence_1 = { c1e81f 8d4c02ff 398dd4fcffff 7d1f }
		$sequence_2 = { ff15???????? 8a4e02 8066030f 0fb7c0 240f 02c0 02c0 }
		$sequence_3 = { e8???????? 83c428 8d7de0 e8???????? 8b450c 8b4d18 8b5514 }
		$sequence_4 = { c745f0c4e9f2e5 c745f4e3f4eff2 66c745f8f900 894dc0 c745c4d3ffc8ff c745c8c5ffccff c745ccccffb3ff }
		$sequence_5 = { 49 894d18 3bc1 7437 8b7d14 8b5708 }
		$sequence_6 = { 8b4d08 8b550c 8d0411 83f802 }
		$sequence_7 = { 7702 2bc2 8b5104 8b3c82 8b4d2c 8b5528 51 }
		$sequence_8 = { 68???????? ff15???????? 8b7508 c7465ca0634200 83660800 33ff 47 }
		$sequence_9 = { 8d75a0 e8???????? 8b5da0 8b4da4 8bc3 2bc1 }

	condition:
		7 of them and filesize <409600
}