rule MALPEDIA_Win_Rm3_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "7719069f-32fe-5972-8438-aed4e36844e7"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.rm3"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.rm3_auto.yar#L1-L378"
		license_url = "N/A"
		logic_hash = "108e288ac75d378107658478aa6294381528e48e962e4f140c133bb5541af046"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d7c13ff 4a f7d2 23fa 3bf8 7609 }
		$sequence_1 = { 8b4138 8b5608 8d5410ff 48 f7d0 }
		$sequence_2 = { 8b45f8 83c628 ff4dfc 85c0 }
		$sequence_3 = { 8931 8b7004 897104 8b4808 ff7004 }
		$sequence_4 = { 034c240c 8b00 51 03c2 50 e8???????? }
		$sequence_5 = { 3bf8 7609 8b413c 8d5418ff eb0a }
		$sequence_6 = { 8b460c 03c2 394508 7303 8975f8 8b45f8 }
		$sequence_7 = { 8b5e10 8d4438ff 4f f7d7 23c7 8d7c13ff 4a }
		$sequence_8 = { 41 ff4508 ff4d0c 885405fc }
		$sequence_9 = { 57 8bc3 8d9568ffffff e8???????? 8b849d64ffffff }
		$sequence_10 = { e8???????? 8b5508 57 8bc3 8d8d58feffff e8???????? }
		$sequence_11 = { 8b750c 50 8db4b558feffff 894510 }
		$sequence_12 = { 8bf0 2b7508 f7de 1bf6 83e60b }
		$sequence_13 = { e8???????? 8bd8 85db 7420 8d45fc }
		$sequence_14 = { e8???????? 2bf3 89750c 0f88b3000000 8d3c1e 8dbcbd58feffff }
		$sequence_15 = { 744b 8975fc 6a18 5e }
		$sequence_16 = { 33d2 4533c0 410fc9 48f7b42488000000 8b15???????? }
		$sequence_17 = { 488bf3 488bce e8???????? 4885c0 488bd8 7415 }
		$sequence_18 = { 4155 4156 4157 4883ec30 4c8b05???????? 49b91ddd6c4f91f44525 }
		$sequence_19 = { 41be18000000 488b15???????? 488b4270 488bc8 48c1e90c 4833c1 488bc8 }
		$sequence_20 = { 57 4154 4155 4156 4157 4883ec20 4c8b05???????? }
		$sequence_21 = { 488bc1 48c1e81b 4833c1 33c9 480fafc3 }
		$sequence_22 = { ff15???????? 85c0 7445 488d4c2468 ff15???????? ff15???????? }
		$sequence_23 = { 488d4c2440 4c8bce 4c8bc5 498bd4 }
		$sequence_24 = { 899568ffffff 89b564ffffff 889d63ffffff 7570 31c0 89855cffffff eb16 }
		$sequence_25 = { 8d0d84308702 31d2 8b75f0 89462c 890c24 }
		$sequence_26 = { 885801 39d7 897db8 8975b4 75d7 8d45d4 }
		$sequence_27 = { a1???????? 6a00 6a00 6a00 6a00 68???????? ffd0 }
		$sequence_28 = { ffd0 8d0dd1318702 890424 894c2404 e8???????? 83f800 }
		$sequence_29 = { 52 8bb5e0fbffff 56 8985d0fbffff 8995ccfbffff 898dc8fbffff ffd7 }
		$sequence_30 = { 8945d0 8b45d0 8b4dd4 8b55ec 01ca 891424 }
		$sequence_31 = { 897dec 8955e8 8975e4 ffd3 83ec10 890424 }
		$sequence_32 = { 53 57 56 83ec20 8b450c 8b4d08 31d2 }
		$sequence_33 = { 890c24 c744240400000000 8955dc e8???????? 8d0d77318702 890424 }
		$sequence_34 = { 8b7834 8b5f3c 8945f0 89f8 01d8 813c1f50450000 }
		$sequence_35 = { 8bbd64fdffff 897e08 8b9d68fdffff 891e }
		$sequence_36 = { c7460cfe308702 c74604???????? 8b35???????? 8985e0fdffff 898ddcfdffff 8995d8fdffff }
		$sequence_37 = { 898dfcfeffff e8???????? 890424 8b853cffffff 89442404 }
		$sequence_38 = { 89e2 894a04 c70204010000 8b15???????? 8985e8fdffff 898de4fdffff }
		$sequence_39 = { 8b5924 89855cffffff 89d8 c1e81e 83e001 }

	condition:
		7 of them and filesize <221184
}