rule MALPEDIA_Win_Startpage_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "bf47ff90-3238-555c-bf4a-537084ae22d6"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.startpage"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.startpage_auto.yar#L1-L133"
		license_url = "N/A"
		logic_hash = "9dae8bd02cc42718a63c04f81edbd9a29e9f4300c24f882a2c1fba0669713697"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8945ec 85db 740c 8b0b 85c9 7406 0fb701 }
		$sequence_1 = { 83eb01 75f1 8b75f8 8b06 33c9 663b08 759d }
		$sequence_2 = { 75f5 2bd1 d1fa 5b 52 ff7508 8bcf }
		$sequence_3 = { 8901 89742410 eb06 8931 8b742410 8b44241c 85c0 }
		$sequence_4 = { 8bec a1???????? 85c0 740e 50 e8???????? 8325????????00 }
		$sequence_5 = { 722e 8b4dc0 40 3d00100000 721a f6c11f 759c }
		$sequence_6 = { 8b03 8bfb 53 ff5004 8b7508 33c9 8bc3 }
		$sequence_7 = { e8???????? 59 c645fc01 8b8de0feffff 83c1f0 e8???????? 51 }
		$sequence_8 = { 755f 8a0a 8d4201 8907 80f975 7553 8b4db8 }
		$sequence_9 = { 8907 50 50 8945fc ff35???????? ff31 }

	condition:
		7 of them and filesize <2277376
}