
rule MALPEDIA_Win_Cueisfry_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "7fd15319-e895-59d1-bc47-6c7854fd0773"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cueisfry"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.cueisfry_auto.yar#L1-L122"
		license_url = "N/A"
		logic_hash = "312c24021c3e8bf9c6e0d5e58840583a4541e92e9f141ae7391f901c409f9736"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ff15???????? b8???????? c3 8b45ec c745fcffffffff 85c0 7406 }
		$sequence_1 = { f3a5 52 e8???????? 8d44241c }
		$sequence_2 = { e8???????? 85c0 750c 55 ff15???????? e9???????? }
		$sequence_3 = { 8944241c 7c0d 80f95a 7f08 0fbee9 }
		$sequence_4 = { 8975dc e8???????? 8b45ec 3bc7 750d }
		$sequence_5 = { 8d4c2408 50 e8???????? b91f000000 33c0 8d7c2431 c644243000 }
		$sequence_6 = { ff15???????? 8bb424a8010000 8d4c240c 51 8bce }
		$sequence_7 = { 5f 5e 5d 32c0 5b 81c424030000 c3 }
		$sequence_8 = { 8d4c240c c68424a001000001 e8???????? 8d8c24ac010000 889c24a0010000 e8???????? }
		$sequence_9 = { 6a00 ff15???????? 68d0070000 ff15???????? 8d94249c000000 6a00 }

	condition:
		7 of them and filesize <81920
}