rule MALPEDIA_Win_Iispy_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "204a2c38-8895-5ac0-a1fb-2cdf3f008fea"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.iispy"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.iispy_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "7326802c4105c66879b54e4bc2a70df2a9f75047a51ff2245fe60a57fbe51d36"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { ebdc 837b1800 0f85f6000000 3bce 7436 8a01 3c5d }
		$sequence_1 = { d1e8 03d0 8b5e0c 8b7d08 2bd9 03fb }
		$sequence_2 = { 85c0 755e f7459c00100000 7503 8b7608 }
		$sequence_3 = { ff2485887a0010 51 8bcf e8???????? 8b17 8b4210 2b420c }
		$sequence_4 = { 6a00 ff75e4 c745e800000000 ffd6 85c0 0f856effffff eb0c }
		$sequence_5 = { 85f6 0f84c1010000 0fb7460e 8bc8 c1e90a f6c101 }
		$sequence_6 = { 0f1145c8 8b4810 894dc4 b903000000 0f1100 6689480e 8d4dc8 }
		$sequence_7 = { 8955b4 8d0409 50 6a00 52 e8???????? b800100000 }
		$sequence_8 = { f6430801 7411 8d5304 8bcf e8???????? 5f 5e }
		$sequence_9 = { 8b742424 8b7c2420 884c240b 89742410 897c241c e9???????? 3bf8 }

	condition:
		7 of them and filesize <397312
}