rule MALPEDIA_Win_Conti_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "aae9ecae-21cf-5ec8-8511-8157ca36f115"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.conti"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.conti_auto.yar#L1-L225"
		license_url = "N/A"
		logic_hash = "0be9a10d7e2a11f01ccc516eb831064a902454185cea8a72f6170734199b0c59"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 56 57 bf0e000000 8d7101 }
		$sequence_1 = { 8d7f01 0fb6c0 b978000000 2bc8 }
		$sequence_2 = { 57 bf0a000000 8d7101 8d5f75 8a06 8d7601 0fb6c0 }
		$sequence_3 = { 8d7f01 0fb6c0 b96c000000 2bc8 }
		$sequence_4 = { 0f1f4000 8a07 8d7f01 0fb6c0 b948000000 }
		$sequence_5 = { 8975fc 803e00 7541 53 bb0a000000 }
		$sequence_6 = { 8975fc 803e00 7542 53 bb0e000000 }
		$sequence_7 = { 8d7f01 0fb6c0 b909000000 2bc8 }
		$sequence_8 = { e8???????? 8bb6007d0000 85f6 75ef 6aff }
		$sequence_9 = { 50 6a20 ff15???????? 68???????? ff15???????? 68???????? }
		$sequence_10 = { 780e 7f07 3d00005000 7605 }
		$sequence_11 = { 8bec 8b4d08 e8???????? 6a00 ff15???????? }
		$sequence_12 = { 50 8b4508 ff7004 ff15???????? 85c0 7508 6a01 }
		$sequence_13 = { 6810660000 ff7508 ff15???????? 85c0 }
		$sequence_14 = { 85ff 7408 57 56 ff15???????? ff75f8 56 }
		$sequence_15 = { 7411 a801 740d 83f001 50 ff7608 }
		$sequence_16 = { 48894c2430 4c8d45ff 488d4d0f 418bd6 48894c2428 488d4d07 48894c2420 }
		$sequence_17 = { 42884c0500 49ffc0 4983f80d 72af 44884d0f }
		$sequence_18 = { 33d2 ffd0 897c2450 b856555555 }
		$sequence_19 = { 0fb64500 0fb645ff 84c0 755c }
		$sequence_20 = { 488b4f30 488b4738 4885c9 7406 }
		$sequence_21 = { 48894c2448 488d55e0 488d4c2470 4533c0 }
		$sequence_22 = { 42884c0501 49ffc0 4983f80c 72af }
		$sequence_23 = { 41b801000000 488bd3 8bcf ffd0 4d85f6 }

	condition:
		7 of them and filesize <520192
}