
rule MALPEDIA_Win_Lcpdot_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "a95a9872-7a8a-5e4e-81d9-79280cf44b78"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.lcpdot"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.lcpdot_auto.yar#L1-L158"
		license_url = "N/A"
		logic_hash = "3aab7a93128b920a2310606f2af0b9275aa227850391bd4e2d60e74544bd69d0"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e9???????? c705????????01000000 e8???????? 83f801 }
		$sequence_1 = { 85c9 0f848c000000 53 56 8b7208 }
		$sequence_2 = { 6a01 52 56 8d8508feffff }
		$sequence_3 = { e8???????? 85c0 752a 56 ff15???????? }
		$sequence_4 = { ff24851e884000 838de8fdffffff 89b588fdffff 89b5bcfdffff }
		$sequence_5 = { 90 488b4308 4885c0 743f 488b0d???????? 488d15ad4f0100 }
		$sequence_6 = { ffd7 5f 5e c3 55 8bec 81ec400c0000 }
		$sequence_7 = { 8d8d14f4ffff 51 ebd8 83c320 53 8bce e8???????? }
		$sequence_8 = { 8b11 8b4228 53 ffd0 33c0 8d55e0 }
		$sequence_9 = { 85c0 0f8514010000 4c8d2d0a2f0100 41b804010000 }
		$sequence_10 = { 488d4c2430 e8???????? b920080000 e8???????? }
		$sequence_11 = { 48894c2408 4881ec88000000 488d0df54d0100 ff15???????? }
		$sequence_12 = { 488bd9 894110 bf04000000 3daa55aa55 7519 }
		$sequence_13 = { 7409 488bcf ff15???????? 33c0 488b9c2470040000 488b8c2440040000 4833cc }
		$sequence_14 = { 488d1d23de0000 488d3d24de0000 eb0e 488b03 4885c0 7402 ffd0 }

	condition:
		7 of them and filesize <257024
}