
rule MALPEDIA_Win_Crypmic_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "50202601-a687-564d-add6-7e6f376e5e2e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.crypmic"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.crypmic_auto.yar#L1-L117"
		license_url = "N/A"
		logic_hash = "9041d9d560914890b77f3fcac1afa5aa11364ed26eb5680a449dc6f4542c2153"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 395818 764a 8b7820 03f9 }
		$sequence_1 = { 2bc1 74ec 46 3b75fc 770b 8b55f8 }
		$sequence_2 = { 8b4de4 894f04 8b4de8 894f08 668b4df0 66894f0c 668b45f2 }
		$sequence_3 = { 33d2 8d642400 8d4001 66890c17 }
		$sequence_4 = { 50 8b4608 6a08 ff7604 ffd0 }
		$sequence_5 = { 33c0 8bcf 66894302 e8???????? }
		$sequence_6 = { 43 83c704 3b5818 72bb 5f }
		$sequence_7 = { 55 8bec 83ec0c 8b413c 53 8b440878 03c1 }
		$sequence_8 = { 5d c20800 8b55fc 8b4224 8d0458 0fb70c08 8b421c }
		$sequence_9 = { 8b440878 03c1 8945fc 395818 }

	condition:
		7 of them and filesize <81920
}