
rule MALPEDIA_Win_Alureon_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "d906ba05-9af9-5358-abd3-33a25815a15f"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.alureon"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.alureon_auto.yar#L1-L161"
		license_url = "N/A"
		logic_hash = "69c2ddac38bf20f21fb2d59f504ac16289e135ccaf5d5c616ac40bfbb62cd466"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 59 32c0 8d7c2420 f3aa 8b4d14 }
		$sequence_1 = { 3b442410 75cf 33c0 5f 5e 5b c20800 }
		$sequence_2 = { 6800001000 8d45f8 50 c745d818000000 }
		$sequence_3 = { 68000010c0 8d45fc 50 c745d818000000 }
		$sequence_4 = { 6800000080 6a03 56 6a01 }
		$sequence_5 = { 41 8bca 49 ffc7 }
		$sequence_6 = { 2bc8 03cf 8908 eb2f 837dfc05 751c }
		$sequence_7 = { 6800005600 8d45d0 50 53 }
		$sequence_8 = { 53 ff15???????? 8945f8 56 }
		$sequence_9 = { c745f000010000 749d ff75e8 ff15???????? }
		$sequence_10 = { 66a5 8d85a8feffff 50 68???????? a4 }
		$sequence_11 = { 741c 8d85e4fbffff 50 8d85f8feffff 50 }
		$sequence_12 = { 837dfc0a 7cc0 eb32 8bc3 }
		$sequence_13 = { 50 33f6 46 56 8d8424cc000000 50 }
		$sequence_14 = { 8d8424ec010000 50 68???????? ff15???????? 85c0 0f84f2020000 }
		$sequence_15 = { ff15???????? 85c0 7409 39b424c8000000 75cf 53 53 }

	condition:
		7 of them and filesize <278528
}