
rule MALPEDIA_Win_Taurus_Stealer_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "1d04f49a-1251-5bc9-a2e1-54ed739ba752"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.taurus_stealer"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.taurus_stealer_auto.yar#L1-L133"
		license_url = "N/A"
		logic_hash = "5a56120ca5bf111c092d7e02323e7c3983f49990178f81f0fd9b64062b85cfef"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 56 8b7508 eb12 8d4e1c e8???????? 8bce e8???????? }
		$sequence_1 = { 8d4de8 e8???????? 85f6 7408 8d4dd0 e8???????? 8b4508 }
		$sequence_2 = { 88550f 88450e 8d450e 51 50 8d4d8c e8???????? }
		$sequence_3 = { 51 50 8bce e8???????? 8d4dcc e8???????? 8d4db4 }
		$sequence_4 = { 7305 8a5df3 ebf1 8d45f4 c645ff00 50 8bd6 }
		$sequence_5 = { 8bc2 c1e802 c1e103 8b0483 d3e8 880432 42 }
		$sequence_6 = { 8d4ddc e8???????? 8d4d90 e8???????? 8d4d84 e8???????? }
		$sequence_7 = { c74610fe33b90f c7461465dc040b c74618e3804800 c7461cb5492c0d c7462045909c0f c74624dd90c504 c7462870e8f00e }
		$sequence_8 = { 0f1145c1 885ddf 0fbe4581 250f000080 7905 48 83c8f0 }
		$sequence_9 = { 40 83f806 7305 8a5df2 ebf1 8d45f3 c645f900 }

	condition:
		7 of them and filesize <524288
}