
rule MALPEDIA_Win_Purplewave_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "bc61a32f-ee96-5e25-892f-9d381408f659"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.purplewave"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.purplewave_auto.yar#L1-L133"
		license_url = "N/A"
		logic_hash = "5efe0dc0002836bd228e34e2c06d2e0edc1c85c62aac77610517f67f8f987125"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? 8d4da4 c645fc12 e8???????? 84db 0f84ca020000 6a40 }
		$sequence_1 = { 0f8415000000 81a53cffffffffbfffff 8d8da8feffff e9???????? c3 8d8d60feffff e9???????? }
		$sequence_2 = { 8d8c2468010000 e8???????? 6a0d e8???????? 59 56 8bd0 }
		$sequence_3 = { 6bc838 57 8b0495201e4900 8a440828 a848 757b 84c0 }
		$sequence_4 = { 8d4dbc e8???????? 8d4dd4 e8???????? 8bc3 e8???????? c20c00 }
		$sequence_5 = { b8???????? e8???????? 8bf9 8db78c000000 8bce e8???????? 84c0 }
		$sequence_6 = { 53 50 e8???????? 83c40c 8d8db8feffff e8???????? 8d95b8feffff }
		$sequence_7 = { 53 68???????? 50 ff5110 ff758c ffd6 50 }
		$sequence_8 = { 0f85d3000000 8d45e8 50 8b06 8b08 83c128 }
		$sequence_9 = { 84c0 750e 8d45d8 50 8d4e6c e8???????? eb49 }

	condition:
		7 of them and filesize <1400832
}