rule MALPEDIA_Win_Torrentlocker_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "56bf47db-a6d1-5792-b5b6-3656138ac949"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.torrentlocker"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.torrentlocker_auto.yar#L1-L170"
		license_url = "N/A"
		logic_hash = "9124185b3dba8eb6288bd309dcd17a816c52adb0e1e08ff17bcd23b3d53099e4"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { c3 83f801 7405 83f802 }
		$sequence_1 = { 8b0d???????? 5f c7000c000000 894804 }
		$sequence_2 = { 85c0 7514 e8???????? 3d00000600 }
		$sequence_3 = { 50 56 6a00 6a01 6a02 ff15???????? }
		$sequence_4 = { 8b0d???????? 890e e8???????? 8bd8 e8???????? 6a00 6a01 }
		$sequence_5 = { 83ec24 6a00 6a01 68???????? ff15???????? 85c0 7551 }
		$sequence_6 = { 56 ff15???????? 83f802 740f 83f803 740a }
		$sequence_7 = { e8???????? 3d00000600 1bc0 40 a3???????? eb05 }
		$sequence_8 = { 83c002 6685c9 75f5 2bc2 d1f8 8d440014 }
		$sequence_9 = { 52 50 ff15???????? 85c0 7519 8b0d???????? 51 }
		$sequence_10 = { 51 6a01 6a00 0d00800000 50 6a00 }
		$sequence_11 = { 8b0d???????? 5f 894e0c 5e }
		$sequence_12 = { 8b0d???????? 6a00 6a00 57 }
		$sequence_13 = { 48 85c0 7ff4 5f 33c0 5e c3 }
		$sequence_14 = { 8b0d???????? 57 6a00 51 ff15???????? 8bc6 }
		$sequence_15 = { c705????????00000000 e8???????? 8bf0 e8???????? }

	condition:
		7 of them and filesize <933888
}