
rule MALPEDIA_Win_Sappycache_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ad4dab53-cb13-5a84-86d5-edc74e26f321"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sappycache"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.sappycache_auto.yar#L1-L118"
		license_url = "N/A"
		logic_hash = "f4483696db263dfbbabb83dfce8ccde9309b112a65cf425cc63ed3dc1fcead40"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 448bcf 895c2428 33d2 33c9 4889442420 488bf0 ff15???????? }
		$sequence_1 = { ff15???????? 85c0 7428 488bcd 488d1545f80000 }
		$sequence_2 = { 488b8188000000 488d0d16fa0000 4883c018 7452 8bd7 0f1000 }
		$sequence_3 = { ff15???????? 41b904000000 c7452060ea0000 4c8d4520 }
		$sequence_4 = { 4c8d0dd6860000 c5f35cca c4c173590cc1 4c8d0da5760000 c5f359c1 }
		$sequence_5 = { 49ffc0 47382c04 75f7 488d157c1f0100 }
		$sequence_6 = { 4c89742430 448bcf 895c2428 33d2 33c9 4889442420 }
		$sequence_7 = { f20f1000 8b7808 e9???????? 488d05eed70000 4a8b0ce8 42f644313880 744d }
		$sequence_8 = { 4c8d0d136d0000 8bf9 488d15ba4d0000 b906000000 4c8d05f66c0000 e8???????? }
		$sequence_9 = { 4180e003 80e30f 41c0e004 440ac0 }

	condition:
		7 of them and filesize <262144
}