
rule MALPEDIA_Win_Tinba_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "8b073df0-6973-5487-9d6c-3a57aeeab821"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tinba"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.tinba_auto.yar#L1-L141"
		license_url = "N/A"
		logic_hash = "3e0ce52a496c3fcf4e972331a3890b233f5a6cdb900c63778e37d0782cfe61e3"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b7508 ad 50 56 }
		$sequence_1 = { 8b4510 aa 8b450c ab }
		$sequence_2 = { 8a241f 88240f 88041f 41 }
		$sequence_3 = { 6a00 6a00 6a00 ff750c 6a00 6a00 ff7508 }
		$sequence_4 = { 8b4114 83f8fd 7506 8b4108 8b4014 85c0 7403 }
		$sequence_5 = { 66b80d0a 66ab b8436f6f6b ab b869653a20 ab }
		$sequence_6 = { ff15???????? 48 83c420 48 85c0 0f84b4000000 }
		$sequence_7 = { 814a3500080000 4c 29c6 40 8832 }
		$sequence_8 = { 8b7d0c 31c9 bb0a000000 31d2 f7f3 52 }
		$sequence_9 = { 8b4514 8908 290e 8b06 }
		$sequence_10 = { 66b80d0a 66ab b855736572 ab b82d416765 ab }
		$sequence_11 = { 73ed 88e8 48 8d1d5a020000 }
		$sequence_12 = { fd 8b7d0c 83c707 8b4508 83e00f }

	condition:
		7 of them and filesize <57344
}