rule MALPEDIA_Win_Longwatch_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "9cbc3845-247e-5088-802c-974faf2556c3"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.longwatch"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.longwatch_auto.yar#L1-L118"
		license_url = "N/A"
		logic_hash = "f16a1609422dbff4c114599f67e44a3d80148789c090def0703b76643a40482b"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 68???????? e8???????? 83c404 833d????????ff 7546 6a00 }
		$sequence_1 = { 8bec 53 8b5d08 33c9 57 33c0 8d3c9d2c074300 }
		$sequence_2 = { 0f8cf8030000 68a1000000 ff15???????? 6683f888 0f8ce3030000 8d46fe }
		$sequence_3 = { eb29 8b55d4 8a07 8b0c95a00b4300 }
		$sequence_4 = { 53 8b5d08 33c9 57 33c0 8d3c9d2c074300 f00fb10f }
		$sequence_5 = { 6bc618 57 8db874074300 57 }
		$sequence_6 = { 8ad3 b9???????? e8???????? 837d9400 8db548ffffff }
		$sequence_7 = { e8???????? ff7364 33c9 8d7b18 84c0 0f44f9 }
		$sequence_8 = { 56 68a0000000 8bf1 ff15???????? }
		$sequence_9 = { c74634d46e4200 6a00 57 8bce e8???????? }

	condition:
		7 of them and filesize <647168
}