
rule MALPEDIA_Win_Sinowal_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "31384acf-e07e-5abe-adce-b44a77e374ec"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sinowal"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.sinowal_auto.yar#L1-L122"
		license_url = "N/A"
		logic_hash = "42d79ca235acd4d3a743286e206901b01ddea7a50a0ec3cebf0e0027f96ae13f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d95bcfdffff 52 e8???????? 83c40c c745f000000000 }
		$sequence_1 = { 8b450c 8b4d08 8d5401ff 8955fc eb12 8b4508 83c001 }
		$sequence_2 = { c745f400000000 c745f800000000 8b4510 8945fc 8b4510 33d2 b908000000 }
		$sequence_3 = { 6a00 8b45f8 50 ff15???????? 8b45f4 }
		$sequence_4 = { 8b0495d0669600 2500000080 8b4df8 8b148dd4669600 81e2ffffff7f 0bc2 }
		$sequence_5 = { 8945d8 c745e400000000 c745fc00000000 68???????? }
		$sequence_6 = { 837d0800 7406 837d0c00 7502 eb64 8b450c }
		$sequence_7 = { 89048dd0669600 8b55fc 8b45fc 8b0c85d0669600 890c95d0669600 8b55fc }
		$sequence_8 = { 890d???????? c705????????00000000 a1???????? 8b0c85d0669600 894dfc }
		$sequence_9 = { c745f400000000 c745f800000000 c745fc00000000 837d0800 7416 837d0c00 7410 }

	condition:
		7 of them and filesize <73728
}