
rule MALPEDIA_Win_Alreay_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "9cdb1d27-466b-525b-895d-ad710c42b112"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.alreay"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.alreay_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "9b54d114d735844c857255b8100f13777f444dd5372ec863d1d85e3d492b2e7d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8bca 83e103 03eb f3aa e9???????? 83fa07 7511 }
		$sequence_1 = { 89b48484010000 8a442418 fec0 885c2420 8b5c2424 88442418 8b442420 }
		$sequence_2 = { 894c2404 7407 b802000000 eb1d 8b90e8010000 85d2 7411 }
		$sequence_3 = { 89442428 85c0 0f850c010000 8b442420 3bc7 7608 8bd7 }
		$sequence_4 = { 8b8574010000 8bd1 23d0 83faff 0f848d000000 3bc3 7c55 }
		$sequence_5 = { 8b15???????? 8b442414 8b742444 8b4c2448 42 40 83c604 }
		$sequence_6 = { 8a16 8bcf 84d2 8bc6 741d 8a10 80fa5c }
		$sequence_7 = { 8b8268020000 3bc1 0f852f040000 8b86b4040000 8bca 8b916c020000 3bd0 }
		$sequence_8 = { bb16000000 3bc3 bf15000000 0f85f5010000 8b7500 8b86cc000000 8bd0 }
		$sequence_9 = { 8d7c2448 83c9ff 33c0 8b54241c f2ae f7d1 49 }

	condition:
		7 of them and filesize <1867776
}