rule MALPEDIA_Win_Evilpony_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "e7d929da-c5f9-5c4e-ba1c-7d2c63753499"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.evilpony"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.evilpony_auto.yar#L1-L131"
		license_url = "N/A"
		logic_hash = "02845c899902aea9d270d9fa0c1670211f713972016e6e56c5e914a4d2e0626d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 746e 33c0 6a2d 40 668945f0 58 6a04 }
		$sequence_1 = { e8???????? 50 53 e8???????? 83c410 6a23 }
		$sequence_2 = { ff15???????? 83f8ff 74d6 8bc7 8b4df8 33cd }
		$sequence_3 = { 034df0 03c1 8b4db8 c14da802 8d8401a1ebd96e 8b4dac }
		$sequence_4 = { 33f6 ff15???????? 85c0 782c 53 8bc7 e8???????? }
		$sequence_5 = { e8???????? c9 c3 55 8bec 83ec18 8b4d08 }
		$sequence_6 = { e8???????? 8d855cffffff 50 c7855cffffff94000000 ff15???????? 83bd6cffffff02 7509 }
		$sequence_7 = { 56 e8???????? 83c40c 43 5f 5e 8bc3 }
		$sequence_8 = { c3 85f6 7436 85ff 7432 53 6a00 }
		$sequence_9 = { 39b5f0f7ffff 0f8495000000 39b5e4f7ffff 0f8489000000 6a04 8d9ddcf7ffff c785dcf7ffff1000efbe }

	condition:
		7 of them and filesize <147456
}