rule MALPEDIA_Win_Heloag_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ef07a0f3-faff-581a-a00e-f3d94c2f2e27"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.heloag"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.heloag_auto.yar#L1-L169"
		license_url = "N/A"
		logic_hash = "d41534ff803a8c13a09a17ccbef4333268f3c2d9e67aea8ce8ca3bb7d4a205eb"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 66ab aa 83c9ff 8bfe 33c0 }
		$sequence_1 = { 8bf7 8bfa 8a15???????? c1e902 f3a5 8bc8 }
		$sequence_2 = { 8d4dbc 51 ffd7 8b45c4 b919000000 }
		$sequence_3 = { 8b0d???????? 51 e8???????? 6a14 e8???????? 8bf0 83c408 }
		$sequence_4 = { f3a4 a2???????? a2???????? a3???????? }
		$sequence_5 = { 7cc4 8b45fc 8b0d???????? 40 }
		$sequence_6 = { 6a00 6a00 ffd0 33c9 a3???????? 85c0 0f95c1 }
		$sequence_7 = { 8d8dacfdffff 68???????? 51 e8???????? 8b55b4 83c41c 66c745b80200 }
		$sequence_8 = { 8b4e0c 3bcd 8b07 89442410 7464 }
		$sequence_9 = { 894b0c 8a48ff fec1 8848ff eb3c 6a01 55 }
		$sequence_10 = { 8b4108 50 e8???????? 6a01 }
		$sequence_11 = { 85c0 7505 a1???????? 8b4c242c }
		$sequence_12 = { 51 53 68???????? 8d4c2420 ff15???????? }
		$sequence_13 = { 8a442413 6a00 8bce 8806 ff15???????? }
		$sequence_14 = { 8b11 8bcf 52 6a00 50 ff15???????? }
		$sequence_15 = { a1???????? 894304 8b5608 895308 8b4e0c 894b0c }

	condition:
		7 of them and filesize <401408
}