
rule MALPEDIA_Win_Thunker_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ef50f850-b9ad-5639-a44d-12383e7ab286"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.thunker"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.thunker_auto.yar#L1-L123"
		license_url = "N/A"
		logic_hash = "9bc1b7f9eb35f46db81209055d59765c3ce32324a39fc618186d9d412df8d09c"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 89c7 50 68???????? 8dbd00feffff 57 e8???????? 83c420 }
		$sequence_1 = { e8???????? 89c6 83feff 7420 }
		$sequence_2 = { 8d8500feffff 50 56 e8???????? 89c7 83ffff }
		$sequence_3 = { e8???????? 83c40c 89c7 e8???????? 8985ecfdffff }
		$sequence_4 = { d1ea 8995e8fdffff 56 e8???????? 6a08 68???????? 68???????? }
		$sequence_5 = { 68204e0000 68d3710000 50 e8???????? 6a00 68804f1200 68dd710000 }
		$sequence_6 = { 83c40c 8d8544edffff 50 e8???????? 8985c4edffff 8b400c }
		$sequence_7 = { 7433 7c79 3df1710000 7447 }
		$sequence_8 = { 8d85f0edffff 50 57 e8???????? 83bdf0eeffff05 752e }
		$sequence_9 = { e8???????? 68???????? e8???????? 83c41c 68???????? 68???????? e8???????? }

	condition:
		7 of them and filesize <73728
}