
rule MALPEDIA_Win_Madmax_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "230eedbf-6cae-5fdd-90b6-aea0b58f95e1"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.madmax"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.madmax_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "8fadf42f6b346841d23791b849b5705de38f9f89679dc44544ef7b477d437506"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { d0cd 99 86d6 4c ae 2f 4e }
		$sequence_1 = { b80c32e173 8ac5 08679e fb 59 8050cb80 baef812a0a }
		$sequence_2 = { e07d d8cc 6a55 60 25a237f301 4a 4c }
		$sequence_3 = { 8d8dd0feffff e8???????? 8db396000000 6a3b 9c f605????????d6 0f851c010000 }
		$sequence_4 = { 93 9f 856d67 664c 8657b6 49 152b9be0c2 }
		$sequence_5 = { d9dd 095527 17 44 4b 60 1f }
		$sequence_6 = { f723 56 c8d95bcc 0e 64a04d98f5db 6e 051e079cc8 }
		$sequence_7 = { ad 7ea5 6abd 650e 9c 3528e563a7 6c }
		$sequence_8 = { f605????????e2 0f851d010000 73e7 f22486 85e6 210a e788 }
		$sequence_9 = { f605????????a5 7531 df2e 8b1b f8 b36a 7928 }

	condition:
		7 of them and filesize <3227648
}