rule MALPEDIA_Win_Getmail_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "44034b05-2864-56ad-b1e2-ce75dcdcb73e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.getmail"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.getmail_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "cb48fd93bd0d8eb21e02a5c1c72974fd0280a8132ab759131eea2bb4b2c53aaf"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 896c2460 e8???????? 8d4c2420 8d9424cc000000 51 8d8424a8000000 52 }
		$sequence_1 = { c68424d000000004 8b040a 813803000930 7508 8b5808 d1eb 80e301 }
		$sequence_2 = { 55 ffd7 68???????? 55 a3???????? ffd7 8b0d???????? }
		$sequence_3 = { 50 8b10 ff5208 391d???????? 0f84a2000000 a1???????? }
		$sequence_4 = { 0f8285feffff 33db 50 e8???????? 83c404 8b442458 50 }
		$sequence_5 = { c3 57 e8???????? 83c404 3bc5 89432c }
		$sequence_6 = { 83f961 7208 83f97a 7703 83e957 c0e004 }
		$sequence_7 = { 8d8c249c000000 8894249c000000 e8???????? 8a442413 6a00 8d8c24ac000000 c68424d400000005 }
		$sequence_8 = { 8bfe 8b11 2bf8 03c5 57 50 }
		$sequence_9 = { 8b8424d8000000 33db 3bc3 899c24cc000000 7505 b8???????? 8b8c24dc000000 }

	condition:
		7 of them and filesize <188416
}