rule MALPEDIA_Win_Naikon_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "2b0fa492-57d4-5b88-95d9-a0b325c3a81c"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.naikon"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.naikon_auto.yar#L1-L125"
		license_url = "N/A"
		logic_hash = "10ad96daf91bea73d71b90a544491c018eb03e29efd792a88809f482c814e2f1"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 881c08 8d4405c9 50 e8???????? 59 8b4d0c 8901 }
		$sequence_1 = { 8d85f8feffff 68???????? 50 e8???????? 8b3d???????? 83c418 8d85a8fcffff }
		$sequence_2 = { ff750c c745f002000000 897dec c745e401000000 57 897de0 ff7508 }
		$sequence_3 = { 53 50 8d85f4fffdff 56 50 ff35???????? }
		$sequence_4 = { 83c418 57 50 8d8528ffffff 50 ffb690000000 e8???????? }
		$sequence_5 = { 6a10 57 681cc10000 897df4 ff750c c745f002000000 }
		$sequence_6 = { 53 53 8b4010 8d4d0c }
		$sequence_7 = { e8???????? 83c40c 837df400 7408 ff75f4 e8???????? }
		$sequence_8 = { 83c41c 33c0 808405dcf9fffffb 40 }
		$sequence_9 = { 6a01 ff35???????? ff15???????? 8bd8 8b4508 46 6a00 }

	condition:
		7 of them and filesize <188416
}