rule MALPEDIA_Win_Shapeshift_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "08e6a360-def4-58d5-989a-762ada20c1ff"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.shapeshift"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.shapeshift_auto.yar#L1-L105"
		license_url = "N/A"
		logic_hash = "c522b147cc687acbd3ced32f880a4cbfad89b8f069e6c6ec7d0ae0159c8619d1"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { e8???????? 33d2 b93b110f00 f7f1 68???????? 8915???????? e8???????? }
		$sequence_1 = { 6a00 6a07 68000000c0 51 ff15???????? }
		$sequence_2 = { 8b45fc 817848d0f74100 7409 ff7048 e8???????? }
		$sequence_3 = { 394508 7c1f 3934bd38054200 7531 e8???????? 8904bd38054200 }
		$sequence_4 = { 6a00 57 e8???????? 8b5dfc 83c410 8b35???????? 53 }
		$sequence_5 = { 8365fc00 8b049d38054200 8b4de0 f644082801 7515 e8???????? c70009000000 }
		$sequence_6 = { c3 3b0d???????? f27502 f2c3 f2e987080000 }
		$sequence_7 = { 6a0c 7550 e8???????? 83c404 8bf8 }

	condition:
		7 of them and filesize <303104
}