
rule MALPEDIA_Win_Remexi_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "687f133c-aa4c-5c82-a16b-c166cd521a0e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.remexi"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.remexi_auto.yar#L1-L209"
		license_url = "N/A"
		logic_hash = "05a94cf7e4fffe2d3333c852ee9c9ff577487ed8e4c35b0a2c90ccf7655ac3b0"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 56 c706ffffffff e8???????? 83c404 }
		$sequence_1 = { 53 50 ff15???????? 3dffffff00 }
		$sequence_2 = { ff15???????? 8bf0 85f6 7513 8b45d8 }
		$sequence_3 = { 68???????? 50 ff15???????? 8b0d???????? 8b35???????? 890d???????? 68???????? }
		$sequence_4 = { 8945e0 8945e4 8945e8 b802000000 }
		$sequence_5 = { ff15???????? 6a10 8d4ddc 8bf0 51 56 ff15???????? }
		$sequence_6 = { 8b95d4feffff 52 6a00 68ffff1f00 ffd7 }
		$sequence_7 = { e8???????? 83ec1c 8bcc 89642430 6aff 53 }
		$sequence_8 = { 52 56 50 e8???????? 8bf0 eb02 }
		$sequence_9 = { 57 e8???????? 6a01 6a00 6a00 ff15???????? }
		$sequence_10 = { 33c0 5f c3 56 ff15???????? 57 8b3d???????? }
		$sequence_11 = { 8b45d8 8b4818 8b5104 50 8955e0 }
		$sequence_12 = { 890d???????? 68???????? 41 50 a3???????? }
		$sequence_13 = { 488bf9 33d2 33c9 e8???????? 488d0d74e90100 4885c0 480f44c1 }
		$sequence_14 = { 488d15fe730200 488d4c2450 e8???????? 90 41b902000000 }
		$sequence_15 = { 0f8333010000 488d4550 483bf0 0f8726010000 }
		$sequence_16 = { 488b0b e8???????? 48c743180f000000 48c7431000000000 c60300 8bc7 488b4c2438 }
		$sequence_17 = { 4883ec40 48c7442428feffffff 48895c2460 4889742468 488b05???????? }
		$sequence_18 = { 488d0527dd0100 488981b8000000 4883a17004000000 b90d000000 }
		$sequence_19 = { 488d4c2470 e8???????? 85c0 750a b902020208 }
		$sequence_20 = { b902010209 e8???????? 90 48837b1810 }

	condition:
		7 of them and filesize <614400
}