rule MALPEDIA_Win_Crenufs_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "f753eb30-be4b-5f62-9991-28649f65a79a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.crenufs"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.crenufs_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "62adacba8819f400983ac2aed5807f2d80c5566db3c1a2873916dcd6fb658c9d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b0c8de0934000 25ff000000 c1ea18 33cb 8b1c95e08f4000 8b56f8 }
		$sequence_1 = { 55 56 57 8bf9 8a4c2444 33ed 884c2425 }
		$sequence_2 = { ff15???????? 56 8d4d90 c645fc05 ff15???????? 56 8d4de0 }
		$sequence_3 = { ffd0 83c408 53 ff15???????? 8b44243c 8b4e08 3bc5 }
		$sequence_4 = { 59 50 57 8d4de0 ff15???????? bf???????? 57 }
		$sequence_5 = { 750c 8b3d???????? 891d???????? 8d4c2444 ff15???????? 3bfb 7409 }
		$sequence_6 = { ff15???????? 8d8d3cf2ffff c645fc03 e8???????? c645fc02 56 }
		$sequence_7 = { 84c0 89542410 743e 3b31 752d 53 56 }
		$sequence_8 = { 8d4c2444 895c2428 895c2430 33ff ff15???????? a1???????? 48 }
		$sequence_9 = { 895dfc e8???????? 8b10 8bc8 ff5210 }

	condition:
		7 of them and filesize <106496
}