rule MALPEDIA_Win_Cryptolocker_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "ef7778bc-4b3f-57b9-be94-b68bbd4e0a82"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cryptolocker"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.cryptolocker_auto.yar#L1-L122"
		license_url = "N/A"
		logic_hash = "308de5ca9cd2927cd67ef4efc7cb0917b58e872fb565dc9ff1066d1520a7dec9"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d4a9f 6683f905 770f c1e004 }
		$sequence_1 = { 0f858f000000 a1???????? 85c0 7509 }
		$sequence_2 = { 898431ecfeffff 8b4ee8 85c9 740e 8b01 }
		$sequence_3 = { ff7720 56 ff15???????? 8b4510 8b4b04 5f 5e }
		$sequence_4 = { 7405 83f802 7549 85c9 }
		$sequence_5 = { 8b75fc 33c9 85c0 0f48f1 7522 85f6 781e }
		$sequence_6 = { c20800 55 8bec 83ec08 53 56 8b7508 }
		$sequence_7 = { 8b4ee8 85c9 740e 8b01 6a01 8b4004 03c8 }
		$sequence_8 = { 55 8bec 56 8b750c 8d8600ffffff 83f801 7723 }
		$sequence_9 = { 0fb7044a 83f820 740f 83f809 7205 83f80d }

	condition:
		7 of them and filesize <778240
}