
rule MALPEDIA_Win_Banatrix_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "dddc42c8-ebb5-5b25-8e19-698be8f181ff"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.banatrix"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.banatrix_auto.yar#L1-L120"
		license_url = "N/A"
		logic_hash = "ad75928262b7ab312e9d49af768e2651c88b8c026115565bb62125e134a2e0bd"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 83ec10 894208 89f7 31c0 f3aa }
		$sequence_1 = { e8???????? 8b4304 85c0 741b c744240800800000 c744240400000000 }
		$sequence_2 = { c744240806000000 893c24 c1e804 40 0fb7c0 }
		$sequence_3 = { 8b5320 0345d0 89542404 890424 }
		$sequence_4 = { e9???????? e8???????? c744240824000000 c744240400000000 }
		$sequence_5 = { 51 c9 c3 55 89e5 57 }
		$sequence_6 = { 83ec10 85c0 8945d4 7542 8b45d0 c744240c04000000 c744240800300000 }
		$sequence_7 = { 8b75d0 8b7dd4 2b7e34 897dcc 7514 8b7304 }
		$sequence_8 = { 83787c00 7511 c704247f000000 e8???????? 31c0 51 eb66 }
		$sequence_9 = { 85c0 56 56 7416 8b03 c745d000000000 }

	condition:
		7 of them and filesize <180224
}