
rule MALPEDIA_Win_Maze_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "107fc7f0-df43-5a49-b2af-87c958bef91f"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.maze"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.maze_auto.yar#L1-L201"
		license_url = "N/A"
		logic_hash = "114687adcaa31dee32acfd0d8a276547892002fc6701cc69c1544ebdb3b57221"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 53 57 56 83ec10 8b4510 8b4d0c }
		$sequence_1 = { 8945f0 c745f000000000 8b45f0 83c410 5e 5f }
		$sequence_2 = { 60 8b7d08 8b4d10 8b450c f3aa 61 8945f0 }
		$sequence_3 = { 83ec10 8b4510 8b4d0c 8b5508 837d0800 8945ec }
		$sequence_4 = { 8945ec 894de8 8955e4 7509 c745f000000000 eb17 60 }
		$sequence_5 = { 89c8 0500000001 83d200 89d7 }
		$sequence_6 = { 89c7 e8???????? 83c40c 57 55 8dbc24f4000000 }
		$sequence_7 = { 89c8 01d6 ba53c6f0ff f7e2 }
		$sequence_8 = { 41 41 41 41 41 41 41 }
		$sequence_9 = { 83ec20 56 be???????? 56 6a00 6801001200 }
		$sequence_10 = { 8d45ec 56 8945f8 6a00 8d45f4 50 c745f40c000000 }
		$sequence_11 = { b904000000 6bd109 8b4d08 8b941100100000 c1ea0a }
		$sequence_12 = { b948040000 b8cccccccc f3ab a1???????? 33c5 8945ec 50 }
		$sequence_13 = { 898d6cfeffff 8b4dfc 8b5508 8b848a10080000 }
		$sequence_14 = { 8b8c1040100000 c1e10a ba04000000 c1e200 8b4508 8b941040100000 c1ea16 }
		$sequence_15 = { 899594fdffff 8b8d9cfdffff 338d98fdffff 038d94fdffff 8b55fc }
		$sequence_16 = { 8b54813c c1e209 8b45fc 8b4d08 8b44813c }
		$sequence_17 = { 8985e4feffff 8b45fc 8b4d08 8b548134 }
		$sequence_18 = { 8b4dfc 8b5508 8b848a1c080000 c1e017 8b4dfc 8b5508 8b8c8a1c080000 }

	condition:
		7 of them and filesize <2318336
}