
rule MALPEDIA_Win_Ghost_Secret_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "1b3488d9-dad5-57ab-8ddb-ae7fa19ffb25"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.ghost_secret"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.ghost_secret_auto.yar#L1-L127"
		license_url = "N/A"
		logic_hash = "36f12490c5a1c42890949e26bd5a0482d94d3f78b5528e6a3d7d1ab5deca281b"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d852cf1ffff 50 e8???????? 8d8548fbffff 50 e8???????? 59 }
		$sequence_1 = { c68424af050000fd c68424b0050000f6 c68424b105000093 c68424b205000038 c68424b305000032 c68424b405000048 c68424b5050000e5 }
		$sequence_2 = { c68424b902000066 c68424ba02000072 c68424bb0200001a c68424bc0200004a }
		$sequence_3 = { c68424e903000052 c68424ea03000082 c68424eb03000058 c68424ec0300008e }
		$sequence_4 = { c684243e030000f0 c684243f030000f2 c68424400300003b c6842441030000c7 c6842454050000ab c684245505000087 c6842456050000d6 }
		$sequence_5 = { 85c0 740b 33c0 5f 5e 5b 8be5 }
		$sequence_6 = { ff15???????? e9???????? a1???????? 33db 3bc7 7e0e 50 }
		$sequence_7 = { c684247c05000006 c684247d0500003e c684247e05000012 c684247f05000053 c684248005000092 c684248105000042 c6842482050000e8 }
		$sequence_8 = { c644247460 c64424751f c6442476e7 c64424778a c6442478dd c68424f40000006a 888c24f5000000 }
		$sequence_9 = { 83c408 5f 5e 81c400200000 c3 81ecfc000000 }

	condition:
		7 of them and filesize <278528
}