rule MALPEDIA_Win_Killdisk_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "fd586ea1-d41c-50af-ab00-4c3fd6d8b593"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.killdisk"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.killdisk_auto.yar#L1-L172"
		license_url = "N/A"
		logic_hash = "5e0faf26e496f52d500cc74a0d402009c944ca198565834d2511070577fb34d3"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d4604 7204 8b08 eb02 8bc8 66891c51 }
		$sequence_1 = { 0f8424020000 8d4c245c b8???????? 8d642400 668b10 }
		$sequence_2 = { 881438 e8???????? 9c c6442408cf 894508 e9???????? }
		$sequence_3 = { 88742408 c70424ba7bbfa4 660fbae408 662dca11 e8???????? 881438 e8???????? }
		$sequence_4 = { 83c40c 68???????? 68e08fc201 e8???????? 8bf0 }
		$sequence_5 = { 8f44241c c64424148e c644240426 e8???????? 4e e8???????? 54 }
		$sequence_6 = { c3 50 ff15???????? 8b8c24d41a0000 }
		$sequence_7 = { 872d???????? 0fc1c2 89e2 66d3c9 66d3c0 }
		$sequence_8 = { e8???????? 84c0 751a a1???????? 50 6802000080 }
		$sequence_9 = { b001 5e 59 c3 837f1800 7413 }
		$sequence_10 = { e8???????? 83c420 6a00 8d442414 }
		$sequence_11 = { 46 66892c24 9c 8d64244c e9???????? 9c 9c }
		$sequence_12 = { 9c 8d642430 e9???????? ff742404 66894500 }
		$sequence_13 = { 8d642454 e9???????? 880424 8774242c 9c 68a12348dd e8???????? }
		$sequence_14 = { 66897c240c 882c24 c64424044f 8d642454 e9???????? }
		$sequence_15 = { 56 e8???????? c1f805 56 8d3c85a098c201 }

	condition:
		7 of them and filesize <10817536
}