rule MALPEDIA_Win_Sys10_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "01030a4d-1840-51b2-a9d0-6bbc4385fa1e"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.sys10"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.sys10_auto.yar#L1-L123"
		license_url = "N/A"
		logic_hash = "6943a43537b8ee069df094c74ea397f99150d4b78d4cfd8ed6ddb44f86656e07"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 6a03 68???????? 68???????? 51 52 50 ff15???????? }
		$sequence_1 = { 837e04ff 740b 8b16 52 e8???????? 83c404 }
		$sequence_2 = { 8b4e0c 51 ff15???????? 8b5608 6aff 52 ff15???????? }
		$sequence_3 = { 56 e8???????? 83c404 85c0 74c6 8b4c2410 896e10 }
		$sequence_4 = { 6810270000 ff15???????? 33c0 59 }
		$sequence_5 = { 837e04ff 740b 8b16 52 }
		$sequence_6 = { 56 89442414 e8???????? 83c404 85c0 7541 }
		$sequence_7 = { 52 6a05 50 ffd6 8b5308 }
		$sequence_8 = { 8d4c2413 51 6800400000 52 50 e8???????? }
		$sequence_9 = { 8b13 52 ffd7 8b4304 50 ffd7 8b4b08 }

	condition:
		7 of them and filesize <286720
}