rule MALPEDIA_Win_Gearshift_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "02540c00-8de2-5ac5-936a-14a6336e7666"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.gearshift"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.gearshift_auto.yar#L1-L126"
		license_url = "N/A"
		logic_hash = "1c8a80ba14390df1b7bcd5e4b955652a287b76aebf22d78fc43b89631a984860"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 4881c4c0000000 5f c3 85c0 0f85a9000000 }
		$sequence_1 = { 4d8bde 4d2b5d30 0f84a1000000 488b4500 488b5d08 }
		$sequence_2 = { 4883ec28 48833d????????00 740a b801000000 4883c428 c3 488d0dc9a80000 }
		$sequence_3 = { 4823f1 66413b7806 0f83ce000000 48895c2448 4c89642450 4c8d25566a0300 4a8d5c003c }
		$sequence_4 = { 83c8ff e9???????? 4c8bfb 4c8be3 488d05363c0300 49c1fc05 }
		$sequence_5 = { 4885c0 0f8418010000 4c8d442470 41b910010000 488bd0 488bcb 48897c2420 }
		$sequence_6 = { 488bd8 ff9688000000 4c8bc3 33d2 488bc8 8947f8 ff96a8000000 }
		$sequence_7 = { 7522 48ffc1 498d0408 493bc3 7cec 4963c2 4803c6 }
		$sequence_8 = { 4533c0 33d2 498bcc 44896c2428 48897c2420 ff15???????? ba01000000 }
		$sequence_9 = { 0fb7d1 eb09 488b4508 488d540102 }

	condition:
		7 of them and filesize <540672
}