
rule MALPEDIA_Win_Darkrat_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "73555b6d-cd36-53aa-b241-54638d6391a7"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.darkrat"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.darkrat_auto.yar#L1-L124"
		license_url = "N/A"
		logic_hash = "e98d828b961bffb4ad606aad50a055367532a60432b86ca76a8c360da1aac44b"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 837de810 895510 8b4804 8d45d4 0f4345d4 2975b4 }
		$sequence_1 = { 51 03f8 52 57 e8???????? 8b45c8 83c40c }
		$sequence_2 = { 51 56 e8???????? 83c40c c6043e00 eb17 57 }
		$sequence_3 = { 8b7dd4 0f8514ffffff 8b55ec 83fa10 }
		$sequence_4 = { 8bd0 b805000000 2bd6 8a0e 8d7601 884c32ff 83e801 }
		$sequence_5 = { e8???????? 83c408 c745e800000000 8d4dd8 }
		$sequence_6 = { 0b510c 52 e8???????? c745fc04000000 e8???????? 84c0 7507 }
		$sequence_7 = { 83c408 c745e800000000 8d4dd8 c745ec0f000000 c645d800 }
		$sequence_8 = { ff75d0 51 8bcb e8???????? 8b75b8 c645fc01 }
		$sequence_9 = { 895510 8b4804 8d45d4 0f4345d4 2975b4 03c6 ff75b4 }

	condition:
		7 of them and filesize <884736
}