
rule MALPEDIA_Win_Tapaoux_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "68d778fd-5462-5b8a-898a-2fe57f5f9d68"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.tapaoux"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.tapaoux_auto.yar#L1-L125"
		license_url = "N/A"
		logic_hash = "f82a0c342c816d1880cfb31489fc94204aa3933a5341062512dc21730819514f"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 83c404 8d9424d0020000 33f6 52 55 ffd3 85c0 }
		$sequence_1 = { f7d1 49 8d7c2454 894c2418 83c9ff f2ae f7d1 }
		$sequence_2 = { 52 50 8d4c2420 68???????? 51 eb49 b900010000 }
		$sequence_3 = { 68???????? 52 ffd6 8d44245c 68???????? 50 }
		$sequence_4 = { 8be8 83fdff 0f84b0000000 8b3d???????? }
		$sequence_5 = { 83c404 8d4c2414 50 51 e8???????? 8d54241c }
		$sequence_6 = { 8d442408 55 50 8d8c241c040000 6800040000 51 56 }
		$sequence_7 = { c3 8d442408 8d4c240c 50 53 53 }
		$sequence_8 = { 68???????? 50 e8???????? 8b07 83c418 85c0 7526 }
		$sequence_9 = { aa 8bb424200c0000 b900010000 33c0 }

	condition:
		7 of them and filesize <294912
}