
rule MALPEDIA_Win_Redsalt_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "295994ac-254e-59ee-b227-ac14e9e1f055"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.redsalt"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.redsalt_auto.yar#L1-L217"
		license_url = "N/A"
		logic_hash = "03f89ce4b045eb8ff5f60169a4045ddc5e403a310ae115cf10989b990183d50a"
		score = 75
		quality = 73
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 750b 68e8030000 ff15???????? e8???????? }
		$sequence_1 = { 83c414 33c9 83f8ff 0f95c1 }
		$sequence_2 = { e8???????? 85c0 750a 6a32 }
		$sequence_3 = { c745d060ea0000 6a04 8d45d0 50 6806100000 }
		$sequence_4 = { 51 ffd6 85c0 7510 }
		$sequence_5 = { 85c0 7515 c705????????01000000 ff15???????? e9???????? }
		$sequence_6 = { 83c9ff 85f6 7c0e 83fe7f 7f09 }
		$sequence_7 = { 6a01 6a00 6a01 6800000080 }
		$sequence_8 = { 7509 80780120 7503 83c002 }
		$sequence_9 = { 8d8530fcffff 50 e8???????? 83c40c }
		$sequence_10 = { 6a00 52 c744242401000000 8944242c c744243002000000 ff15???????? }
		$sequence_11 = { c60100 5f 5e 33c0 }
		$sequence_12 = { 83c40c eb02 33c0 8b4df4 }
		$sequence_13 = { e8???????? 83c408 6800010000 68???????? }
		$sequence_14 = { c1fa04 c0e302 0ad3 83c004 }
		$sequence_15 = { 833800 750f c705????????01000000 e9???????? }
		$sequence_16 = { eb03 83caff 8b442410 c0e106 }
		$sequence_17 = { f7e7 8bea d1ed 33c0 83ef03 8a06 83c603 }
		$sequence_18 = { c644243423 c644243572 c64424367a c644243700 }
		$sequence_19 = { c8201cdd f7be5b408d58 1b7f01 d2cc }
		$sequence_20 = { d2cc bbe3b46b7e 6aa2 dd45ff }
		$sequence_21 = { e8???????? 85ed 4863cd 488be8 }
		$sequence_22 = { e8???????? 8905???????? 48488b942498020000 488b8c2490020000 }
		$sequence_23 = { e8???????? 8903 83f8ff 0f858e3e0b00 }
		$sequence_24 = { e8???????? 8905???????? 4883c428 7502 }

	condition:
		7 of them and filesize <2957312
}