rule MALPEDIA_Win_Acidbox_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "d24270e3-4ecb-5df0-834e-54ac9b4880c3"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.acidbox"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.acidbox_auto.yar#L1-L127"
		license_url = "N/A"
		logic_hash = "7566f8c225df846294fd9c5a92e8c14928b074fdcd922768eae6047a40a5ef6e"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 418bb590000000 4903f4 4889742438 413b8594000000 0f8311010000 397e0c 0f8408010000 }
		$sequence_1 = { 4154 4155 4156 4157 4883ec28 4c8b7128 448b6108 }
		$sequence_2 = { c780d8feffffd3731048 c780dcfeffffffff00ff c780e0feffffffe0cccc c780e4feffffffff0000 4d8920 4d8921 }
		$sequence_3 = { 0fb6ca 4103c9 4403f0 0fb74562 41d3e0 418bc9 49ffc7 }
		$sequence_4 = { ff15???????? 8d043e 898318170000 eb2f 8d8702010000 }
		$sequence_5 = { 4883c438 c3 488bc4 48895810 48897018 57 4154 }
		$sequence_6 = { eb09 4584c0 7908 418b4124 89442420 85c0 }
		$sequence_7 = { 4c8b4de0 c70705000000 f7471000040000 0f840c010000 8b5f48 413bdd 410f47dd }
		$sequence_8 = { 7d07 8bd7 413bc7 7d03 418bd1 8b4b28 488b4310 }
		$sequence_9 = { 0fb79f02040000 418b8a14170000 418bc3 2bc3 }

	condition:
		7 of them and filesize <589824
}