rule MALPEDIA_Win_Htbot_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "9061a5e4-8534-51fe-80a9-1a440b66e0d7"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.htbot"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.htbot_auto.yar#L1-L128"
		license_url = "N/A"
		logic_hash = "90f98baa748c169d2b4b8297454f9f854e4138797b2c83ac6d83acccfa4dd9b0"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 6a00 68???????? 51 ff15???????? 85c0 7524 }
		$sequence_1 = { 56 57 8b7c2440 8b474c 89442414 c7474c00000000 }
		$sequence_2 = { 8908 8b15???????? 8d0c52 83c2ff a3???????? 8d4488f8 8b0d???????? }
		$sequence_3 = { 8b11 50 8b4204 ffd0 8bc5 e9???????? 8d77f0 }
		$sequence_4 = { 51 8bc8 ffd2 8bf8 85ff 0f84ccfeffff 8b4604 }
		$sequence_5 = { 83f801 7e68 8d4d02 6a22 51 }
		$sequence_6 = { 83c010 894510 c684244402000003 a1???????? 8b500c b9???????? ffd2 }
		$sequence_7 = { 8903 c744241c00000000 8b7c2424 8b4708 83c708 8378f400 c744241001000000 }
		$sequence_8 = { 83c010 894514 c684244402000004 a1???????? 8b500c }
		$sequence_9 = { 51 ff15???????? 8d46f0 8d500c 83c9ff f00fc10a 49 }

	condition:
		7 of them and filesize <196608
}