rule MALPEDIA_Win_Bluehaze_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "b806577a-57c1-570d-aa1c-22fa8aae198a"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.bluehaze"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.bluehaze_auto.yar#L1-L130"
		license_url = "N/A"
		logic_hash = "e848ac1af15ccfaaa261b6df2c92e0cbc62750d10a2cd1c781f26efdf23885e7"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8d85f0feffff 50 8bcf ff15???????? 8b08 8b4904 }
		$sequence_1 = { 745f 6a30 c7460800000000 e8???????? 83c404 85c0 }
		$sequence_2 = { 0fbe56ff 4e 51 52 57 ffd3 83c40c }
		$sequence_3 = { e8???????? 83c408 8bc8 ff15???????? 397314 7204 }
		$sequence_4 = { 8d4f04 894e30 894e34 8d4708 8d4d10 894610 894614 }
		$sequence_5 = { 68???????? 64a100000000 50 81ecec050000 a1???????? 33c5 8945ec }
		$sequence_6 = { 83c420 8d14c500000000 2bd0 8b06 5b 8d0cd0 }
		$sequence_7 = { 03c2 894508 753d 8b4604 8b0e 3bc8 0f8466010000 }
		$sequence_8 = { 0b0b 010b 0b0b 0b0b 0b0b 0b0b 0b0b }
		$sequence_9 = { 33db 8bc7 8bf1 c745e80f000000 895de4 885dd4 8d5001 }

	condition:
		7 of them and filesize <424960
}