
rule MALPEDIA_Win_Pipemon_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "fb1257dc-1899-57a8-9bb3-37873100ec17"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.pipemon"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.pipemon_auto.yar#L1-L121"
		license_url = "N/A"
		logic_hash = "a7cf49399560b8b73200f34644a487f3922c8589009d7d641339ef3a3238ec7b"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 418bf8 4903fe 85db 0f84a1000000 6690 49634e3c }
		$sequence_1 = { 7516 488d05bd360100 488b4c2430 483bc8 7405 e8???????? 488b05???????? }
		$sequence_2 = { 85c0 7427 488b4c2438 488d1526d90000 ff15???????? }
		$sequence_3 = { b906000000 48898620020000 0fb7c0 66f3ab 488d3d2c3b0100 }
		$sequence_4 = { 488d4c2438 e8???????? 4c8d4820 4889442420 4c8bc3 488d5590 488d4c2438 }
		$sequence_5 = { 4881c458010000 c3 83f801 7529 b803000000 488b8c2440010000 4833cc }
		$sequence_6 = { 458d4d02 458bc7 488d542450 488bc8 }
		$sequence_7 = { e8???????? 4881c498000000 c3 448b442430 488d1543fe0100 33c0 488d4c2440 }
		$sequence_8 = { ffc8 3d03010000 7734 488d44244c 488bd7 }
		$sequence_9 = { 80bd8008000000 0f84b6010000 4d85ed 0f84b6000000 }

	condition:
		7 of them and filesize <389120
}