
rule MALPEDIA_Win_Badhatch_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "e8145868-3ca1-5c30-b22c-ef0d5f024b54"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.badhatch"
		source_url = "https://github.com/malpedia/signator-rules//blob/fbacfc09b84d53d410385e66a8e56f25016c588a/rules/win.badhatch_auto.yar#L1-L128"
		license_url = "N/A"
		logic_hash = "a465c1cdccc061411fd4300f0446fb5369592ae409bf62acf36666de581c3980"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 53 6a00 50 ffd7 56 6a00 ff35???????? }
		$sequence_1 = { 8b7730 59 59 8975f0 85f6 7514 }
		$sequence_2 = { 8bc7 99 0145e0 1155e4 eb0e }
		$sequence_3 = { ff7618 ff15???????? 85c0 740e ff15???????? 8945e4 e9???????? }
		$sequence_4 = { 8bf0 59 85f6 750e eb40 ff15???????? 8bf0 }
		$sequence_5 = { 8945e4 ff45d0 e9???????? 395de4 0f8574060000 68???????? ff7618 }
		$sequence_6 = { 50 ff15???????? 85c0 0f8524010000 8d45ec 50 8d8594f5ffff }
		$sequence_7 = { 8bd8 48 83e90c 85db 75f1 5b }
		$sequence_8 = { 5e c9 c3 55 8bec 83e4f8 81ec38020000 }
		$sequence_9 = { 50 ff15???????? 8945ec 3bc3 7509 }

	condition:
		7 of them and filesize <156672
}