name: Create a YaraX binary release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.yar'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install yara-x

    - name: Run script
      run: python scripts/builder.py
