name: Release YARA Bundle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 * *'  # Runs monthly on the 1st at 03:00 UTC

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set version and tag
        id: version
        run: |
          YY=$(date +'%y')         # e.g. 25
          MM=$(date +'%m')         # e.g. 06
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            PATCH=100
          else
            PATCH=0
          fi
          VERSION="v$YY.$MM.$PATCH"
          TAG_NAME="YARA Bundle ${VERSION}"
          FILE_NAME="yara_bundle_${VERSION}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT

      - name: Prepare bundle files
        run: |
          mkdir -p bundle
          # Copy all .yar files preserving folder structure
          find rules -type f -name '*.yar' -exec cp --parents {} bundle/ \;
          # Copy the specific PowerShell script
          mkdir -p bundle/scripts
          cp scripts/windows.ps1 bundle/scripts/

      - name: Create archive
        run: tar -czf "${{ steps.version.outputs.file_name }}.tar.gz" -C bundle .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.tag_name }}
          draft: false
          generate_release_notes: true
          files: ${{ steps.version.outputs.file_name }}.tar.gz
