name: Validate YARA Rules on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  yara-validation:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install YARA-X
        run: brew install yara-x

      - name: Find changed .yar files
        id: yarafiles
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.yar$' || true)
          echo "Changed YARA files:"
          echo "$CHANGED_FILES"
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run YARA validation
        id: validate
        run: |
          chmod +x scripts/lint_yara.sh
          scripts/lint_yara.sh ${{ steps.yarafiles.outputs.files }}

      - name: Comment PR with result
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const message = `${{ steps.validate.outputs.message }}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
