name: Validate YARA Rules on PR

on:
  pull_request:
    branches: [ main ]

jobs:
  yara-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # FULL history for git diff to work
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Install YARA and yls-yara
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip install yls-yara

      - name: Find changed .yar files
        id: yarafiles
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.yar$' || true)
          echo "Changed YARA files:"
          echo "$CHANGED_FILES"
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run validation script
        id: validate
        run: |
          chmod +x scripts/lint_yara.sh
          scripts/lint_yara.sh ${{ steps.yarafiles.outputs.files }}

      - name: Comment PR with result
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ steps.check.outputs.message }}`
            })
