name: Validate YARA Rules on PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering in an open PR

jobs:
  yara-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Needed to detect changed files

      - name: Install YARA and yls-yara
        run: |
          sudo apt-get update && sudo apt-get install -y yara python3-pip
          pip install yls-yara

      - name: Find changed .yar files
        id: yarafiles
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | grep '\.yar$' || true)
          echo "Changed YARA files:"
          echo "$CHANGED_FILES"
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Validate and Lint YARA files
        id: check
        run: |
          FILES="${{ steps.yarafiles.outputs.files }}"
          echo "Processing files:"
          echo "$FILES"

          if [ -z "$FILES" ]; then
            echo "No .yar files changed in this PR."
            echo "message=No YARA files to check ✅" >> $GITHUB_OUTPUT
            exit 0
          fi

          ERRORS=""
          for file in $FILES; do
            echo "▶ Validating syntax for $file"
            if ! yara -C "$file" 2>&1; then
              ERRORS+="\n❌ Syntax error in $file"
              continue
            else
              echo "✅ $file passed syntax check"
            fi

            echo "▶ Linting $file"
            if ! yls lint "$file"; then
              ERRORS+="\n⚠️ Lint issues in $file"
            else
              echo "✅ $file passed lint"
            fi
          done

          if [ -n "$ERRORS" ]; then
            echo -e "Issues found:$ERRORS"
            echo "message=Some YARA files failed checks:$ERRORS" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "All YARA files passed validation and linting."
            echo "message=✅ All YARA files passed validation and linting." >> $GITHUB_OUTPUT
          fi

      - name: Comment PR with result
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `${{ steps.check.outputs.message }}`
            })
